name: quadplane
description: ArduPilot quadplane parameters
version: schema
schema_params:
- QWIK_ANGLE_MAX
- QWIK_AUTO_FILTER
- QWIK_AUTO_SAVE
- QWIK_AXES
- QWIK_DOUBLE_TIME
- QWIK_ENABLE
- QWIK_GAIN_MARGIN
- QWIK_OPTIONS
- QWIK_OSC_SMAX
- QWIK_REDUCE_MAX
- QWIK_RP_PI_RATIO
- QWIK_YAW_D_MAX
- QWIK_YAW_P_MAX
- QWIK_Y_PI_RATIO
- Q_ACRO_PIT_RATE
- Q_ACRO_RLL_RATE
- Q_ACRO_YAW_RATE
- Q_APPROACH_DIST
- Q_ASSIST_ALT
- Q_ASSIST_ANGLE
- Q_ASSIST_DELAY
- Q_ASSIST_OPTIONS
- Q_ASSIST_SPEED
- Q_AUTOTUNE_AGGR
- Q_AUTOTUNE_AXES
- Q_AUTOTUNE_GMBK
- Q_AUTOTUNE_MIN_D
- Q_A_ACC_P_MAX
- Q_A_ACC_R_MAX
- Q_A_ACC_Y_MAX
- Q_A_ANGLE_BOOST
- Q_A_ANGLE_MAX
- Q_A_ANG_LIM_TC
- Q_A_ANG_PIT_P
- Q_A_ANG_RLL_P
- Q_A_ANG_YAW_P
- Q_A_INPUT_TC
- Q_A_LAND_P_MULT
- Q_A_LAND_R_MULT
- Q_A_LAND_Y_MULT
- Q_A_RATE_FF_ENAB
- Q_A_RATE_P_MAX
- Q_A_RATE_R_MAX
- Q_A_RATE_WPY_MAX
- Q_A_RATE_Y_MAX
- Q_A_RAT_PIT_D
- Q_A_RAT_PIT_D_FF
- Q_A_RAT_PIT_FF
- Q_A_RAT_PIT_FLTD
- Q_A_RAT_PIT_FLTE
- Q_A_RAT_PIT_FLTT
- Q_A_RAT_PIT_I
- Q_A_RAT_PIT_IMAX
- Q_A_RAT_PIT_NEF
- Q_A_RAT_PIT_NTF
- Q_A_RAT_PIT_P
- Q_A_RAT_PIT_PDMX
- Q_A_RAT_PIT_SMAX
- Q_A_RAT_RLL_D
- Q_A_RAT_RLL_D_FF
- Q_A_RAT_RLL_FF
- Q_A_RAT_RLL_FLTD
- Q_A_RAT_RLL_FLTE
- Q_A_RAT_RLL_FLTT
- Q_A_RAT_RLL_I
- Q_A_RAT_RLL_IMAX
- Q_A_RAT_RLL_NEF
- Q_A_RAT_RLL_NTF
- Q_A_RAT_RLL_P
- Q_A_RAT_RLL_PDMX
- Q_A_RAT_RLL_SMAX
- Q_A_RAT_YAW_D
- Q_A_RAT_YAW_D_FF
- Q_A_RAT_YAW_FF
- Q_A_RAT_YAW_FLTD
- Q_A_RAT_YAW_FLTE
- Q_A_RAT_YAW_FLTT
- Q_A_RAT_YAW_I
- Q_A_RAT_YAW_IMAX
- Q_A_RAT_YAW_NEF
- Q_A_RAT_YAW_NTF
- Q_A_RAT_YAW_P
- Q_A_RAT_YAW_PDMX
- Q_A_RAT_YAW_SMAX
- Q_A_THR_G_BOOST
- Q_A_THR_MIX_MAN
- Q_A_THR_MIX_MAX
- Q_A_THR_MIX_MIN
- Q_BACKTRANS_MS
- Q_BCK_PIT_LIM
- Q_ENABLE
- Q_ESC_CAL
- Q_FRAME_CLASS
- Q_FRAME_TYPE
- Q_FWD_MANTHR_MAX
- Q_FWD_PIT_LIM
- Q_FWD_THR_GAIN
- Q_FWD_THR_USE
- Q_FW_LND_APR_RAD
- Q_GUIDED_MODE
- Q_LAND_ALTCHG
- Q_LAND_FINAL_ALT
- Q_LAND_FINAL_SPD
- Q_LAND_ICE_CUT
- Q_LOIT_ACC_MAX_M
- Q_LOIT_ANG_MAX
- Q_LOIT_BRK_ACC_M
- Q_LOIT_BRK_DELAY
- Q_LOIT_BRK_JRK_M
- Q_LOIT_OPTIONS
- Q_LOIT_SPEED_MS
- Q_MAV_TYPE
- Q_M_BAT_CURR_MAX
- Q_M_BAT_CURR_TC
- Q_M_BAT_IDX
- Q_M_BAT_VOLT_MAX
- Q_M_BAT_VOLT_MIN
- Q_M_BOOST_SCALE
- Q_M_HOVER_LEARN
- Q_M_IDLE_SEC
- Q_M_OPTIONS
- Q_M_PWM_MAX
- Q_M_PWM_MIN
- Q_M_PWM_TYPE
- Q_M_SAFE_DISARM
- Q_M_SAFE_TIME
- Q_M_SLEW_DN_TIME
- Q_M_SLEW_UP_TIME
- Q_M_SPIN_ARM
- Q_M_SPIN_MAX
- Q_M_SPIN_MIN
- Q_M_SPOOL_TIME
- Q_M_SPOOL_TIM_DN
- Q_M_THST_EXPO
- Q_M_THST_HOVER
- Q_M_YAW_HEADROOM
- Q_M_YAW_SV_ANGLE
- Q_NAVALT_MIN
- Q_OPTIONS
- Q_PILOT_ACCEL_Z
- Q_PILOT_SPD_DN
- Q_PILOT_SPD_UP
- Q_PLT_Y_EXPO
- Q_PLT_Y_RATE
- Q_PLT_Y_RATE_TC
- Q_P_ANGLE_MAX
- Q_P_D_ACC_D
- Q_P_D_ACC_D_FF
- Q_P_D_ACC_FF
- Q_P_D_ACC_FLTD
- Q_P_D_ACC_FLTE
- Q_P_D_ACC_FLTT
- Q_P_D_ACC_I
- Q_P_D_ACC_IMAX
- Q_P_D_ACC_NEF
- Q_P_D_ACC_NTF
- Q_P_D_ACC_P
- Q_P_D_ACC_PDMX
- Q_P_D_ACC_SMAX
- Q_P_D_POS_P
- Q_P_D_VEL_D
- Q_P_D_VEL_FF
- Q_P_D_VEL_FLTD
- Q_P_D_VEL_FLTE
- Q_P_D_VEL_I
- Q_P_D_VEL_IMAX
- Q_P_D_VEL_P
- Q_P_JERK_D
- Q_P_JERK_NE
- Q_P_NE_POS_P
- Q_P_NE_VEL_D
- Q_P_NE_VEL_FF
- Q_P_NE_VEL_FLTD
- Q_P_NE_VEL_FLTE
- Q_P_NE_VEL_I
- Q_P_NE_VEL_IMAX
- Q_P_NE_VEL_P
- Q_RC_SPEED
- Q_RTL_ALT
- Q_RTL_ALT_MIN
- Q_RTL_MODE
- Q_TAILSIT_ANGLE
- Q_TAILSIT_ANG_VT
- Q_TAILSIT_DSKLD
- Q_TAILSIT_ENABLE
- Q_TAILSIT_GSCMAX
- Q_TAILSIT_GSCMIN
- Q_TAILSIT_GSCMSK
- Q_TAILSIT_INPUT
- Q_TAILSIT_MIN_VO
- Q_TAILSIT_MOTMX
- Q_TAILSIT_RAT_FW
- Q_TAILSIT_RAT_VT
- Q_TAILSIT_RLL_MX
- Q_TAILSIT_THR_VT
- Q_TAILSIT_VFGAIN
- Q_TAILSIT_VHGAIN
- Q_TAILSIT_VHPOW
- Q_TAILSIT_VT_P_P
- Q_TAILSIT_VT_R_P
- Q_TAILSIT_VT_Y_P
- Q_THROTTLE_EXPO
- Q_THRST_LOSS_OPT
- Q_TILT_ENABLE
- Q_TILT_FIX_ANGLE
- Q_TILT_FIX_GAIN
- Q_TILT_MASK
- Q_TILT_MAX
- Q_TILT_RATE_DN
- Q_TILT_RATE_UP
- Q_TILT_TYPE
- Q_TILT_WING_FLAP
- Q_TILT_YAW_ANGLE
- Q_TKOFF_ARSP_LIM
- Q_TKOFF_FAIL_SCL
- Q_TKOFF_RPM_MAX
- Q_TKOFF_RPM_MIN
- Q_TRANSITION_MS
- Q_TRANS_DECEL
- Q_TRANS_FAIL
- Q_TRANS_FAIL_ACT
- Q_TRAN_PIT_MAX
- Q_TRIM_PITCH
- Q_VFWD_ALT
- Q_VFWD_GAIN
- Q_WP_ACC
- Q_WP_ACC_CNR
- Q_WP_ACC_Z
- Q_WP_JERK
- Q_WP_RADIUS_M
- Q_WP_RFND_USE
- Q_WP_SPD
- Q_WP_SPD_DN
- Q_WP_SPD_UP
- Q_WP_TER_MARGIN
- Q_WVANE_ANG_MIN
- Q_WVANE_ENABLE
- Q_WVANE_GAIN
- Q_WVANE_HGT_MIN
- Q_WVANE_LAND
- Q_WVANE_OPTIONS
- Q_WVANE_SPD_MAX
- Q_WVANE_TAKEOFF
- Q_WVANE_VELZ_MAX
- Q_YAW_RATE_MAX
