params:
  ARSPD2_TYPE: 0
  ARSPD_AUTOCAL: 1
  ARSPD_BUS: 1
  ARSPD_DEVID: 141313
  ARSPD_OFFSET: 75.10670471191406
  ARSPD_OFF_PCNT: 0
  ARSPD_OPTIONS: 11
  ARSPD_PIN: 15
  ARSPD_PRIMARY: 0
  ARSPD_PSI_RANGE: 1
  ARSPD_RATIO: 2.9880690574645996
  ARSPD_SKIP_CAL: 0
  ARSPD_TUBE_ORDR: 2
  ARSPD_TYPE: 1
  ARSPD_USE: 1
  ARSPD_WIND_GATE: 5
  ARSPD_WIND_MAX: 0
  ARSPD_WIND_WARN: 0
