params:
  GPS1_CAN_NODEID: 0
  GPS1_CAN_OVRIDE: 0
  GPS1_COM_PORT: 1
  GPS1_DELAY_MS: 0
  GPS1_GNSS_MODE: 0
  GPS1_MB_TYPE: 0
  GPS1_POS_X: 0
  GPS1_POS_Y: 0
  GPS1_POS_Z: 0
  GPS1_RATE_MS: 200
  GPS1_TYPE: 1
  GPS2_CAN_NODEID: 0
  GPS2_CAN_OVRIDE: 0
  GPS2_COM_PORT: 1
  GPS2_DELAY_MS: 0
  GPS2_GNSS_MODE: 0
  GPS2_MB_TYPE: 0
  GPS2_POS_X: 0
  GPS2_POS_Y: 0
  GPS2_POS_Z: 0
  GPS2_RATE_MS: 200
  GPS2_TYPE: 14
  GPS_AUTO_CONFIG: 1
  GPS_AUTO_SWITCH: 0
  GPS_BLEND_MASK: 5
  GPS_DRV_OPTIONS: 0
  GPS_INJECT_TO: 127
  GPS_MIN_ELEV: -100
  GPS_NAVFILTER: 8
  GPS_PRIMARY: 0
  GPS_RAW_DATA: 0
  GPS_SAVE_CFG: 2
  GPS_SBAS_MODE: 2
  GPS_SBP_LOGMASK: -256
