name: mavlink
description: ArduPilot mavlink parameters
version: schema
schema_params:
- MAV10_ADSB
- MAV10_EXTRA1
- MAV10_EXTRA2
- MAV10_EXTRA3
- MAV10_EXT_STAT
- MAV10_OPTIONS
- MAV10_PARAMS
- MAV10_POSITION
- MAV10_RAW_CTRL
- MAV10_RAW_SENS
- MAV10_RC_CHAN
- MAV11_ADSB
- MAV11_EXTRA1
- MAV11_EXTRA2
- MAV11_EXTRA3
- MAV11_EXT_STAT
- MAV11_OPTIONS
- MAV11_PARAMS
- MAV11_POSITION
- MAV11_RAW_CTRL
- MAV11_RAW_SENS
- MAV11_RC_CHAN
- MAV12_ADSB
- MAV12_EXTRA1
- MAV12_EXTRA2
- MAV12_EXTRA3
- MAV12_EXT_STAT
- MAV12_OPTIONS
- MAV12_PARAMS
- MAV12_POSITION
- MAV12_RAW_CTRL
- MAV12_RAW_SENS
- MAV12_RC_CHAN
- MAV13_ADSB
- MAV13_EXTRA1
- MAV13_EXTRA2
- MAV13_EXTRA3
- MAV13_EXT_STAT
- MAV13_OPTIONS
- MAV13_PARAMS
- MAV13_POSITION
- MAV13_RAW_CTRL
- MAV13_RAW_SENS
- MAV13_RC_CHAN
- MAV14_ADSB
- MAV14_EXTRA1
- MAV14_EXTRA2
- MAV14_EXTRA3
- MAV14_EXT_STAT
- MAV14_OPTIONS
- MAV14_PARAMS
- MAV14_POSITION
- MAV14_RAW_CTRL
- MAV14_RAW_SENS
- MAV14_RC_CHAN
- MAV15_ADSB
- MAV15_EXTRA1
- MAV15_EXTRA2
- MAV15_EXTRA3
- MAV15_EXT_STAT
- MAV15_OPTIONS
- MAV15_PARAMS
- MAV15_POSITION
- MAV15_RAW_CTRL
- MAV15_RAW_SENS
- MAV15_RC_CHAN
- MAV16_ADSB
- MAV16_EXTRA1
- MAV16_EXTRA2
- MAV16_EXTRA3
- MAV16_EXT_STAT
- MAV16_OPTIONS
- MAV16_PARAMS
- MAV16_POSITION
- MAV16_RAW_CTRL
- MAV16_RAW_SENS
- MAV16_RC_CHAN
- MAV17_ADSB
- MAV17_EXTRA1
- MAV17_EXTRA2
- MAV17_EXTRA3
- MAV17_EXT_STAT
- MAV17_OPTIONS
- MAV17_PARAMS
- MAV17_POSITION
- MAV17_RAW_CTRL
- MAV17_RAW_SENS
- MAV17_RC_CHAN
- MAV18_ADSB
- MAV18_EXTRA1
- MAV18_EXTRA2
- MAV18_EXTRA3
- MAV18_EXT_STAT
- MAV18_OPTIONS
- MAV18_PARAMS
- MAV18_POSITION
- MAV18_RAW_CTRL
- MAV18_RAW_SENS
- MAV18_RC_CHAN
- MAV19_ADSB
- MAV19_EXTRA1
- MAV19_EXTRA2
- MAV19_EXTRA3
- MAV19_EXT_STAT
- MAV19_OPTIONS
- MAV19_PARAMS
- MAV19_POSITION
- MAV19_RAW_CTRL
- MAV19_RAW_SENS
- MAV19_RC_CHAN
- MAV1_ADSB
- MAV1_EXTRA1
- MAV1_EXTRA2
- MAV1_EXTRA3
- MAV1_EXT_STAT
- MAV1_OPTIONS
- MAV1_PARAMS
- MAV1_POSITION
- MAV1_RAW_CTRL
- MAV1_RAW_SENS
- MAV1_RC_CHAN
- MAV20_ADSB
- MAV20_EXTRA1
- MAV20_EXTRA2
- MAV20_EXTRA3
- MAV20_EXT_STAT
- MAV20_OPTIONS
- MAV20_PARAMS
- MAV20_POSITION
- MAV20_RAW_CTRL
- MAV20_RAW_SENS
- MAV20_RC_CHAN
- MAV21_ADSB
- MAV21_EXTRA1
- MAV21_EXTRA2
- MAV21_EXTRA3
- MAV21_EXT_STAT
- MAV21_OPTIONS
- MAV21_PARAMS
- MAV21_POSITION
- MAV21_RAW_CTRL
- MAV21_RAW_SENS
- MAV21_RC_CHAN
- MAV22_ADSB
- MAV22_EXTRA1
- MAV22_EXTRA2
- MAV22_EXTRA3
- MAV22_EXT_STAT
- MAV22_OPTIONS
- MAV22_PARAMS
- MAV22_POSITION
- MAV22_RAW_CTRL
- MAV22_RAW_SENS
- MAV22_RC_CHAN
- MAV23_ADSB
- MAV23_EXTRA1
- MAV23_EXTRA2
- MAV23_EXTRA3
- MAV23_EXT_STAT
- MAV23_OPTIONS
- MAV23_PARAMS
- MAV23_POSITION
- MAV23_RAW_CTRL
- MAV23_RAW_SENS
- MAV23_RC_CHAN
- MAV24_ADSB
- MAV24_EXTRA1
- MAV24_EXTRA2
- MAV24_EXTRA3
- MAV24_EXT_STAT
- MAV24_OPTIONS
- MAV24_PARAMS
- MAV24_POSITION
- MAV24_RAW_CTRL
- MAV24_RAW_SENS
- MAV24_RC_CHAN
- MAV25_ADSB
- MAV25_EXTRA1
- MAV25_EXTRA2
- MAV25_EXTRA3
- MAV25_EXT_STAT
- MAV25_OPTIONS
- MAV25_PARAMS
- MAV25_POSITION
- MAV25_RAW_CTRL
- MAV25_RAW_SENS
- MAV25_RC_CHAN
- MAV26_ADSB
- MAV26_EXTRA1
- MAV26_EXTRA2
- MAV26_EXTRA3
- MAV26_EXT_STAT
- MAV26_OPTIONS
- MAV26_PARAMS
- MAV26_POSITION
- MAV26_RAW_CTRL
- MAV26_RAW_SENS
- MAV26_RC_CHAN
- MAV27_ADSB
- MAV27_EXTRA1
- MAV27_EXTRA2
- MAV27_EXTRA3
- MAV27_EXT_STAT
- MAV27_OPTIONS
- MAV27_PARAMS
- MAV27_POSITION
- MAV27_RAW_CTRL
- MAV27_RAW_SENS
- MAV27_RC_CHAN
- MAV28_ADSB
- MAV28_EXTRA1
- MAV28_EXTRA2
- MAV28_EXTRA3
- MAV28_EXT_STAT
- MAV28_OPTIONS
- MAV28_PARAMS
- MAV28_POSITION
- MAV28_RAW_CTRL
- MAV28_RAW_SENS
- MAV28_RC_CHAN
- MAV29_ADSB
- MAV29_EXTRA1
- MAV29_EXTRA2
- MAV29_EXTRA3
- MAV29_EXT_STAT
- MAV29_OPTIONS
- MAV29_PARAMS
- MAV29_POSITION
- MAV29_RAW_CTRL
- MAV29_RAW_SENS
- MAV29_RC_CHAN
- MAV2_ADSB
- MAV2_EXTRA1
- MAV2_EXTRA2
- MAV2_EXTRA3
- MAV2_EXT_STAT
- MAV2_OPTIONS
- MAV2_PARAMS
- MAV2_POSITION
- MAV2_RAW_CTRL
- MAV2_RAW_SENS
- MAV2_RC_CHAN
- MAV30_ADSB
- MAV30_EXTRA1
- MAV30_EXTRA2
- MAV30_EXTRA3
- MAV30_EXT_STAT
- MAV30_OPTIONS
- MAV30_PARAMS
- MAV30_POSITION
- MAV30_RAW_CTRL
- MAV30_RAW_SENS
- MAV30_RC_CHAN
- MAV31_ADSB
- MAV31_EXTRA1
- MAV31_EXTRA2
- MAV31_EXTRA3
- MAV31_EXT_STAT
- MAV31_OPTIONS
- MAV31_PARAMS
- MAV31_POSITION
- MAV31_RAW_CTRL
- MAV31_RAW_SENS
- MAV31_RC_CHAN
- MAV32_ADSB
- MAV32_EXTRA1
- MAV32_EXTRA2
- MAV32_EXTRA3
- MAV32_EXT_STAT
- MAV32_OPTIONS
- MAV32_PARAMS
- MAV32_POSITION
- MAV32_RAW_CTRL
- MAV32_RAW_SENS
- MAV32_RC_CHAN
- MAV3_ADSB
- MAV3_EXTRA1
- MAV3_EXTRA2
- MAV3_EXTRA3
- MAV3_EXT_STAT
- MAV3_OPTIONS
- MAV3_PARAMS
- MAV3_POSITION
- MAV3_RAW_CTRL
- MAV3_RAW_SENS
- MAV3_RC_CHAN
- MAV4_ADSB
- MAV4_EXTRA1
- MAV4_EXTRA2
- MAV4_EXTRA3
- MAV4_EXT_STAT
- MAV4_OPTIONS
- MAV4_PARAMS
- MAV4_POSITION
- MAV4_RAW_CTRL
- MAV4_RAW_SENS
- MAV4_RC_CHAN
- MAV5_ADSB
- MAV5_EXTRA1
- MAV5_EXTRA2
- MAV5_EXTRA3
- MAV5_EXT_STAT
- MAV5_OPTIONS
- MAV5_PARAMS
- MAV5_POSITION
- MAV5_RAW_CTRL
- MAV5_RAW_SENS
- MAV5_RC_CHAN
- MAV6_ADSB
- MAV6_EXTRA1
- MAV6_EXTRA2
- MAV6_EXTRA3
- MAV6_EXT_STAT
- MAV6_OPTIONS
- MAV6_PARAMS
- MAV6_POSITION
- MAV6_RAW_CTRL
- MAV6_RAW_SENS
- MAV6_RC_CHAN
- MAV7_ADSB
- MAV7_EXTRA1
- MAV7_EXTRA2
- MAV7_EXTRA3
- MAV7_EXT_STAT
- MAV7_OPTIONS
- MAV7_PARAMS
- MAV7_POSITION
- MAV7_RAW_CTRL
- MAV7_RAW_SENS
- MAV7_RC_CHAN
- MAV8_ADSB
- MAV8_EXTRA1
- MAV8_EXTRA2
- MAV8_EXTRA3
- MAV8_EXT_STAT
- MAV8_OPTIONS
- MAV8_PARAMS
- MAV8_POSITION
- MAV8_RAW_CTRL
- MAV8_RAW_SENS
- MAV8_RC_CHAN
- MAV9_ADSB
- MAV9_EXTRA1
- MAV9_EXTRA2
- MAV9_EXTRA3
- MAV9_EXT_STAT
- MAV9_OPTIONS
- MAV9_PARAMS
- MAV9_POSITION
- MAV9_RAW_CTRL
- MAV9_RAW_SENS
- MAV9_RC_CHAN
- MAV_GCS_SYSID
- MAV_GCS_SYSID_HI
- MAV_OPTIONS
- MAV_SYSID
- MAV_TELEM_DELAY
