name: flight_control
description: ArduPilot flight_control parameters
version: schema
schema_params:
- ACRO_LOCKING
- ACRO_PITCH_RATE
- ACRO_ROLL_RATE
- ACRO_YAW_RATE
- AIRSPEED_CRUISE
- AIRSPEED_MAX
- AIRSPEED_MIN
- AIRSPEED_STALL
- ALT_OFFSET
- ALT_SLOPE_MAXHGT
- ALT_SLOPE_MIN
- AUTOTUNE_AXES
- AUTOTUNE_LEVEL
- AUTOTUNE_OPTIONS
- CLIMB_SLOPE_HGT
- CRASH_ACC_THRESH
- CRASH_DETECT
- CRUISE_ALT_FLOOR
- DSPOILER_AILMTCH
- DSPOILER_CROW_W1
- DSPOILER_CROW_W2
- DSPOILER_OPTS
- DSPOILR_RUD_RATE
- FBWB_CLIMB_RATE
- FBWB_ELEV_REV
- FLAP_1_PERCNT
- FLAP_1_SPEED
- FLAP_2_PERCNT
- FLAP_2_SPEED
- FLAP_SLEWRATE
- FLIGHT_OPTIONS
- FLTMODE1
- FLTMODE2
- FLTMODE3
- FLTMODE4
- FLTMODE5
- FLTMODE6
- FLTMODE_CH
- FORMAT_VERSION
- FS_EKF_THRESH
- FS_GCS_ENABL
- FS_LONG_ACTN
- FS_LONG_TIMEOUT
- FS_SHORT_ACTN
- FWD_BAT_IDX
- FWD_BAT_THR_CUT
- FWD_BAT_VOLT_MAX
- FWD_BAT_VOLT_MIN
- GCS_PID_MASK
- GROUND_STEER_ALT
- GROUND_STEER_DPS
- GUIDED_D
- GUIDED_D_FF
- GUIDED_FF
- GUIDED_FLTD
- GUIDED_FLTE
- GUIDED_FLTT
- GUIDED_I
- GUIDED_IMAX
- GUIDED_NEF
- GUIDED_NTF
- GUIDED_P
- GUIDED_PDMX
- GUIDED_SMAX
- GUIDED_TIMEOUT
- HOME_RESET_ALT
- INITIAL_MODE
- KFF_RDDRMIX
- KFF_THR2PTCH
- LEVEL_ROLL_LIMIT
- LOG_BITMASK
- MANUAL_RCMASK
- MAN_EXPO_PITCH
- MAN_EXPO_ROLL
- MAN_EXPO_RUDDER
- MIN_GROUNDSPEED
- MIXING_GAIN
- MIXING_OFFSET
- NAVL1_DAMPING
- NAVL1_LIM_BANK
- NAVL1_PERIOD
- NAVL1_XTRACK_I
- ONESHOT_MASK
- OVERRIDE_CHAN
- PTCH2SRV_RLL
- PTCH2SRV_RMAX_DN
- PTCH2SRV_RMAX_UP
- PTCH2SRV_TCONST
- PTCH_LIM_MAX_DEG
- PTCH_LIM_MIN_DEG
- PTCH_RATE_D
- PTCH_RATE_D_FF
- PTCH_RATE_FF
- PTCH_RATE_FLTD
- PTCH_RATE_FLTE
- PTCH_RATE_FLTT
- PTCH_RATE_I
- PTCH_RATE_IMAX
- PTCH_RATE_NEF
- PTCH_RATE_NTF
- PTCH_RATE_P
- PTCH_RATE_PDMX
- PTCH_RATE_SMAX
- PTCH_TRIM_DEG
- RLL2SRV_RMAX
- RLL2SRV_TCONST
- RLL_RATE_D
- RLL_RATE_D_FF
- RLL_RATE_FF
- RLL_RATE_FLTD
- RLL_RATE_FLTE
- RLL_RATE_FLTT
- RLL_RATE_I
- RLL_RATE_IMAX
- RLL_RATE_NEF
- RLL_RATE_NTF
- RLL_RATE_P
- RLL_RATE_PDMX
- RLL_RATE_SMAX
- RNGFND_LANDING
- RNGFND_LND_DIST
- RNGFND_LND_ORNT
- ROLL_LIMIT_DEG
- RTL_ALTITUDE
- RTL_AUTOLAND
- RTL_CLIMB_MIN
- RTL_RADIUS
- RUDDER_ONLY
- RUDD_DT_GAIN
- SCALING_SPEED
- STAB_PITCH_DOWN
- STALL_PREVENTION
- STEER2SRV_D
- STEER2SRV_DRTFCT
- STEER2SRV_DRTMIN
- STEER2SRV_DRTSPD
- STEER2SRV_FF
- STEER2SRV_I
- STEER2SRV_IMAX
- STEER2SRV_MINSPD
- STEER2SRV_P
- STEER2SRV_TCONST
- STICK_MIXING
- TECS_APPR_SMAX
- TECS_CLMB_MAX
- TECS_FLARE_HGT
- TECS_HDEM_TCONST
- TECS_HGT_OMEGA
- TECS_INTEG_GAIN
- TECS_LAND_ARSPD
- TECS_LAND_DAMP
- TECS_LAND_IGAIN
- TECS_LAND_PDAMP
- TECS_LAND_PMAX
- TECS_LAND_SINK
- TECS_LAND_SPDWGT
- TECS_LAND_SRC
- TECS_LAND_TCONST
- TECS_LAND_TDAMP
- TECS_LAND_THR
- TECS_OPTIONS
- TECS_PITCH_MAX
- TECS_PITCH_MIN
- TECS_PTCH_DAMP
- TECS_PTCH_FF_K
- TECS_PTCH_FF_V0
- TECS_RLL2THR
- TECS_SINK_MAX
- TECS_SINK_MIN
- TECS_SPDWEIGHT
- TECS_SPD_OMEGA
- TECS_SYNAIRSPEED
- TECS_THR_DAMP
- TECS_THR_ERATE
- TECS_TIME_CONST
- TECS_TKOFF_IGAIN
- TECS_VERT_ACC
- TERRAIN_FOLLOW
- TERRAIN_LOOKAHD
- THROTTLE_NUDGE
- THR_FAILSAFE
- THR_FS_VALUE
- THR_MAX
- THR_MIN
- THR_PASS_STAB
- THR_SLEWRATE
- THR_SUPP_MAN
- TKOFF_ACCEL_CNT
- TKOFF_FLAP_PCNT
- TKOFF_OPTIONS
- TKOFF_PLIM_SEC
- TKOFF_ROTATE_SPD
- TKOFF_TDRAG_ELEV
- TKOFF_TDRAG_SPD1
- TKOFF_THR_DELAY
- TKOFF_THR_IDLE
- TKOFF_THR_MAX
- TKOFF_THR_MAX_T
- TKOFF_THR_MIN
- TKOFF_THR_MINACC
- TKOFF_THR_MINSPD
- TKOFF_THR_SLEW
- TKOFF_TIMEOUT
- TRIM_THROTTLE
- USE_REV_THRUST
- WP_LOITER_RAD
- WP_MAX_RADIUS
- WP_RADIUS
- YAW2SRV_DAMP
- YAW2SRV_IMAX
- YAW2SRV_INT
- YAW2SRV_RLL
- YAW2SRV_SLIP
- YAW_RATE_D
- YAW_RATE_D_FF
- YAW_RATE_ENABLE
- YAW_RATE_FF
- YAW_RATE_FLTD
- YAW_RATE_FLTE
- YAW_RATE_FLTT
- YAW_RATE_I
- YAW_RATE_IMAX
- YAW_RATE_NEF
- YAW_RATE_NTF
- YAW_RATE_P
- YAW_RATE_PDMX
- YAW_RATE_SMAX
