params:
  BATT_MONITOR: 4
  BATT_CAPACITY: 5000
  BATT_VOLT_PIN: 10
  BATT_CURR_PIN: 11
  BATT_VOLT_MULT: 11.0
  BATT_AMP_PERVLT: 17.0
  BATT_LOW_VOLT: 21.0
  BATT_CRT_VOLT: 19.8
  BATT_ARM_VOLT: 22.2
  BATT_FS_LOW_ACT: 1
  BATT_FS_CRT_ACT: 1
