params:
  LOG_BACKEND_TYPE: 1
  LOG_DARM_RATEMAX: 0
  LOG_DISARMED: 0
  LOG_FILE_BUFSIZE: 200
  LOG_FILE_DSRMROT: 1
  LOG_FILE_MB_FREE: 10
  LOG_FILE_RATEMAX: 0
  LOG_FILE_TIMEOUT: 5
  LOG_MAV_BUFSIZE: 8
  LOG_MAV_RATEMAX: 0
  LOG_MAX_FILES: 500
  LOG_REPLAY: 0
