name: board
description: ArduPilot board parameters
version: schema
schema_params:
- BRD_ALT_CONFIG
- BRD_BOOT_DELAY
- BRD_HEAT_I
- BRD_HEAT_IMAX
- BRD_HEAT_LOWMGN
- BRD_HEAT_P
- BRD_HEAT_TARG
- BRD_IDLE_STATS
- BRD_IO_DSHOT
- BRD_IO_ENABLE
- BRD_OPTIONS
- BRD_PWM_VOLT_SEL
- BRD_RADIO_ABLVL
- BRD_RADIO_ABTIME
- BRD_RADIO_BZOFS
- BRD_RADIO_DEBUG
- BRD_RADIO_DISCRC
- BRD_RADIO_FCCTST
- BRD_RADIO_PPSCH
- BRD_RADIO_PROT
- BRD_RADIO_SIGCH
- BRD_RADIO_STKMD
- BRD_RADIO_TELEM
- BRD_RADIO_TESTCH
- BRD_RADIO_TPPSCH
- BRD_RADIO_TSIGCH
- BRD_RADIO_TXMAX
- BRD_RADIO_TXPOW
- BRD_RADIO_TYPE
- BRD_RTC_TYPES
- BRD_RTC_TZ_MIN
- BRD_SAFETYOPTION
- BRD_SAFETY_DEFLT
- BRD_SAFETY_MASK
- BRD_SBUS_OUT
- BRD_SD_FENCE
- BRD_SD_MISSION
- BRD_SD_SLOWDOWN
- BRD_SER1_RTSCTS
- BRD_SER2_RTSCTS
- BRD_SER3_RTSCTS
- BRD_SER4_RTSCTS
- BRD_SER5_RTSCTS
- BRD_SER6_RTSCTS
- BRD_SER7_RTSCTS
- BRD_SER8_RTSCTS
- BRD_SERIAL_NUM
- BRD_TYPE
- BRD_VBUS_MIN
- BRD_VSERVO_MIN
