name: mount
description: ArduPilot mount parameters
version: schema
schema_params:
- MNT1_DEFLT_MODE
- MNT1_DEVID
- MNT1_LEAD_PTCH
- MNT1_LEAD_RLL
- MNT1_NEUTRAL_X
- MNT1_NEUTRAL_Y
- MNT1_NEUTRAL_Z
- MNT1_OPTIONS
- MNT1_PITCH_MAX
- MNT1_PITCH_MIN
- MNT1_RC_RATE
- MNT1_RETRACT_X
- MNT1_RETRACT_Y
- MNT1_RETRACT_Z
- MNT1_ROLL_MAX
- MNT1_ROLL_MIN
- MNT1_SYSID_DFLT
- MNT1_TYPE
- MNT1_YAW_MAX
- MNT1_YAW_MIN
- MNT2_DEFLT_MODE
- MNT2_DEVID
- MNT2_LEAD_PTCH
- MNT2_LEAD_RLL
- MNT2_NEUTRAL_X
- MNT2_NEUTRAL_Y
- MNT2_NEUTRAL_Z
- MNT2_OPTIONS
- MNT2_PITCH_MAX
- MNT2_PITCH_MIN
- MNT2_RC_RATE
- MNT2_RETRACT_X
- MNT2_RETRACT_Y
- MNT2_RETRACT_Z
- MNT2_ROLL_MAX
- MNT2_ROLL_MIN
- MNT2_SYSID_DFLT
- MNT2_TYPE
- MNT2_YAW_MAX
- MNT2_YAW_MIN
