name: networking
description: ArduPilot networking parameters
version: schema
schema_params:
- DDS_DOMAIN_ID
- DDS_ENABLE
- DDS_IP0
- DDS_IP1
- DDS_IP2
- DDS_IP3
- DDS_MAX_RETRY
- DDS_TIMEOUT_MS
- DDS_UDP_PORT
- MSP_OPTIONS
- MSP_OSD_NCELLS
- NET_DHCP
- NET_ENABLE
- NET_GWADDR0
- NET_GWADDR1
- NET_GWADDR2
- NET_GWADDR3
- NET_IPADDR0
- NET_IPADDR1
- NET_IPADDR2
- NET_IPADDR3
- NET_MACADDR0
- NET_MACADDR1
- NET_MACADDR2
- NET_MACADDR3
- NET_MACADDR4
- NET_MACADDR5
- NET_NETMASK
- NET_OPTIONS
- NET_P1_IP0
- NET_P1_IP1
- NET_P1_IP2
- NET_P1_IP3
- NET_P1_PORT
- NET_P1_PROTOCOL
- NET_P1_TYPE
- NET_P2_IP0
- NET_P2_IP1
- NET_P2_IP2
- NET_P2_IP3
- NET_P2_PORT
- NET_P2_PROTOCOL
- NET_P2_TYPE
- NET_P3_IP0
- NET_P3_IP1
- NET_P3_IP2
- NET_P3_IP3
- NET_P3_PORT
- NET_P3_PROTOCOL
- NET_P3_TYPE
- NET_P4_IP0
- NET_P4_IP1
- NET_P4_IP2
- NET_P4_IP3
- NET_P4_PORT
- NET_P4_PROTOCOL
- NET_P4_TYPE
- NET_REMPPP_IP0
- NET_REMPPP_IP1
- NET_REMPPP_IP2
- NET_REMPPP_IP3
- NET_TESTS
- NET_TEST_IP0
- NET_TEST_IP1
- NET_TEST_IP2
- NET_TEST_IP3
