name: temperature
description: ArduPilot temperature parameters
version: schema
schema_params:
- TEMP10_A0
- TEMP10_A1
- TEMP10_A2
- TEMP10_A3
- TEMP10_A4
- TEMP10_A5
- TEMP10_ADDR
- TEMP10_BUS
- TEMP10_MSG_ID
- TEMP10_PIN
- TEMP10_RTD_NOM
- TEMP10_RTD_REF
- TEMP10_SRC
- TEMP10_SRC_ID
- TEMP10_TYPE
- TEMP11_A0
- TEMP11_A1
- TEMP11_A2
- TEMP11_A3
- TEMP11_A4
- TEMP11_A5
- TEMP11_ADDR
- TEMP11_BUS
- TEMP11_MSG_ID
- TEMP11_PIN
- TEMP11_RTD_NOM
- TEMP11_RTD_REF
- TEMP11_SRC
- TEMP11_SRC_ID
- TEMP11_TYPE
- TEMP12_A0
- TEMP12_A1
- TEMP12_A2
- TEMP12_A3
- TEMP12_A4
- TEMP12_A5
- TEMP12_ADDR
- TEMP12_BUS
- TEMP12_MSG_ID
- TEMP12_PIN
- TEMP12_RTD_NOM
- TEMP12_RTD_REF
- TEMP12_SRC
- TEMP12_SRC_ID
- TEMP12_TYPE
- TEMP13_A0
- TEMP13_A1
- TEMP13_A2
- TEMP13_A3
- TEMP13_A4
- TEMP13_A5
- TEMP13_ADDR
- TEMP13_BUS
- TEMP13_MSG_ID
- TEMP13_PIN
- TEMP13_RTD_NOM
- TEMP13_RTD_REF
- TEMP13_SRC
- TEMP13_SRC_ID
- TEMP13_TYPE
- TEMP14_A0
- TEMP14_A1
- TEMP14_A2
- TEMP14_A3
- TEMP14_A4
- TEMP14_A5
- TEMP14_ADDR
- TEMP14_BUS
- TEMP14_MSG_ID
- TEMP14_PIN
- TEMP14_RTD_NOM
- TEMP14_RTD_REF
- TEMP14_SRC
- TEMP14_SRC_ID
- TEMP14_TYPE
- TEMP15_A0
- TEMP15_A1
- TEMP15_A2
- TEMP15_A3
- TEMP15_A4
- TEMP15_A5
- TEMP15_ADDR
- TEMP15_BUS
- TEMP15_MSG_ID
- TEMP15_PIN
- TEMP15_RTD_NOM
- TEMP15_RTD_REF
- TEMP15_SRC
- TEMP15_SRC_ID
- TEMP15_TYPE
- TEMP1_A0
- TEMP1_A1
- TEMP1_A2
- TEMP1_A3
- TEMP1_A4
- TEMP1_A5
- TEMP1_ADDR
- TEMP1_BUS
- TEMP1_MSG_ID
- TEMP1_PIN
- TEMP1_RTD_NOM
- TEMP1_RTD_REF
- TEMP1_SRC
- TEMP1_SRC_ID
- TEMP1_TYPE
- TEMP2_A0
- TEMP2_A1
- TEMP2_A2
- TEMP2_A3
- TEMP2_A4
- TEMP2_A5
- TEMP2_ADDR
- TEMP2_BUS
- TEMP2_MSG_ID
- TEMP2_PIN
- TEMP2_RTD_NOM
- TEMP2_RTD_REF
- TEMP2_SRC
- TEMP2_SRC_ID
- TEMP2_TYPE
- TEMP3_A0
- TEMP3_A1
- TEMP3_A2
- TEMP3_A3
- TEMP3_A4
- TEMP3_A5
- TEMP3_ADDR
- TEMP3_BUS
- TEMP3_MSG_ID
- TEMP3_PIN
- TEMP3_RTD_NOM
- TEMP3_RTD_REF
- TEMP3_SRC
- TEMP3_SRC_ID
- TEMP3_TYPE
- TEMP4_A0
- TEMP4_A1
- TEMP4_A2
- TEMP4_A3
- TEMP4_A4
- TEMP4_A5
- TEMP4_ADDR
- TEMP4_BUS
- TEMP4_MSG_ID
- TEMP4_PIN
- TEMP4_RTD_NOM
- TEMP4_RTD_REF
- TEMP4_SRC
- TEMP4_SRC_ID
- TEMP4_TYPE
- TEMP5_A0
- TEMP5_A1
- TEMP5_A2
- TEMP5_A3
- TEMP5_A4
- TEMP5_A5
- TEMP5_ADDR
- TEMP5_BUS
- TEMP5_MSG_ID
- TEMP5_PIN
- TEMP5_RTD_NOM
- TEMP5_RTD_REF
- TEMP5_SRC
- TEMP5_SRC_ID
- TEMP5_TYPE
- TEMP6_A0
- TEMP6_A1
- TEMP6_A2
- TEMP6_A3
- TEMP6_A4
- TEMP6_A5
- TEMP6_ADDR
- TEMP6_BUS
- TEMP6_MSG_ID
- TEMP6_PIN
- TEMP6_RTD_NOM
- TEMP6_RTD_REF
- TEMP6_SRC
- TEMP6_SRC_ID
- TEMP6_TYPE
- TEMP7_A0
- TEMP7_A1
- TEMP7_A2
- TEMP7_A3
- TEMP7_A4
- TEMP7_A5
- TEMP7_ADDR
- TEMP7_BUS
- TEMP7_MSG_ID
- TEMP7_PIN
- TEMP7_RTD_NOM
- TEMP7_RTD_REF
- TEMP7_SRC
- TEMP7_SRC_ID
- TEMP7_TYPE
- TEMP8_A0
- TEMP8_A1
- TEMP8_A2
- TEMP8_A3
- TEMP8_A4
- TEMP8_A5
- TEMP8_ADDR
- TEMP8_BUS
- TEMP8_MSG_ID
- TEMP8_PIN
- TEMP8_RTD_NOM
- TEMP8_RTD_REF
- TEMP8_SRC
- TEMP8_SRC_ID
- TEMP8_TYPE
- TEMP9_A0
- TEMP9_A1
- TEMP9_A2
- TEMP9_A3
- TEMP9_A4
- TEMP9_A5
- TEMP9_ADDR
- TEMP9_BUS
- TEMP9_MSG_ID
- TEMP9_PIN
- TEMP9_RTD_NOM
- TEMP9_RTD_REF
- TEMP9_SRC
- TEMP9_SRC_ID
- TEMP9_TYPE
- TEMP_LOG
