name: ekf
description: ArduPilot ekf parameters
version: schema
schema_params:
- EK2_ABIAS_P_NSE
- EK2_ACC_P_NSE
- EK2_ALT_M_NSE
- EK2_ALT_SOURCE
- EK2_BCN_DELAY
- EK2_BCN_I_GTE
- EK2_BCN_M_NSE
- EK2_CHECK_SCALE
- EK2_EAS_I_GATE
- EK2_EAS_M_NSE
- EK2_ENABLE
- EK2_FLOW_DELAY
- EK2_FLOW_I_GATE
- EK2_FLOW_M_NSE
- EK2_FLOW_USE
- EK2_GBIAS_P_NSE
- EK2_GLITCH_RAD
- EK2_GPS_CHECK
- EK2_GPS_TYPE
- EK2_GSCL_P_NSE
- EK2_GSF_RST_MAX
- EK2_GSF_RUN_MASK
- EK2_GSF_USE_MASK
- EK2_GYRO_P_NSE
- EK2_HGT_DELAY
- EK2_HGT_I_GATE
- EK2_HRT_FILT
- EK2_IMU_MASK
- EK2_MAGB_P_NSE
- EK2_MAGE_P_NSE
- EK2_MAG_CAL
- EK2_MAG_EF_LIM
- EK2_MAG_I_GATE
- EK2_MAG_MASK
- EK2_MAG_M_NSE
- EK2_MAX_FLOW
- EK2_NOAID_M_NSE
- EK2_OGN_HGT_MASK
- EK2_OPTIONS
- EK2_POSNE_M_NSE
- EK2_POS_I_GATE
- EK2_RNG_I_GATE
- EK2_RNG_M_NSE
- EK2_RNG_USE_HGT
- EK2_RNG_USE_SPD
- EK2_TAU_OUTPUT
- EK2_TERR_GRAD
- EK2_VELD_M_NSE
- EK2_VELNE_M_NSE
- EK2_VEL_I_GATE
- EK2_WIND_PSCALE
- EK2_WIND_P_NSE
- EK2_YAW_I_GATE
- EK2_YAW_M_NSE
- EK3_ABIAS_P_NSE
- EK3_ACC_BIAS_LIM
- EK3_ACC_P_NSE
- EK3_AFFINITY
- EK3_ALT_M_NSE
- EK3_BCN_DELAY
- EK3_BCN_I_GTE
- EK3_BCN_M_NSE
- EK3_BETA_MASK
- EK3_CHECK_SCALE
- EK3_DRAG_BCOEF_X
- EK3_DRAG_BCOEF_Y
- EK3_DRAG_MCOEF
- EK3_DRAG_M_NSE
- EK3_EAS_I_GATE
- EK3_EAS_M_NSE
- EK3_ENABLE
- EK3_ERR_THRESH
- EK3_FLOW_DELAY
- EK3_FLOW_I_GATE
- EK3_FLOW_MAX
- EK3_FLOW_M_NSE
- EK3_FLOW_USE
- EK3_GBIAS_P_NSE
- EK3_GLITCH_RAD
- EK3_GND_EFF_DZ
- EK3_GPS_CHECK
- EK3_GPS_VACC_MAX
- EK3_GSF_RST_MAX
- EK3_GSF_RUN_MASK
- EK3_GSF_USE_MASK
- EK3_GYRO_P_NSE
- EK3_HGT_DELAY
- EK3_HGT_I_GATE
- EK3_HRT_FILT
- EK3_IMU_MASK
- EK3_LOG_LEVEL
- EK3_MAGB_P_NSE
- EK3_MAGE_P_NSE
- EK3_MAG_CAL
- EK3_MAG_EF_LIM
- EK3_MAG_I_GATE
- EK3_MAG_MASK
- EK3_MAG_M_NSE
- EK3_NOAID_M_NSE
- EK3_OGNM_TEST_SF
- EK3_OGN_HGT_MASK
- EK3_OPTIONS
- EK3_POSNE_M_NSE
- EK3_POS_I_GATE
- EK3_PRIMARY
- EK3_RNG_I_GATE
- EK3_RNG_M_NSE
- EK3_RNG_USE_HGT
- EK3_RNG_USE_SPD
- EK3_SRC1_POSXY
- EK3_SRC1_POSZ
- EK3_SRC1_VELXY
- EK3_SRC1_VELZ
- EK3_SRC1_YAW
- EK3_SRC2_POSXY
- EK3_SRC2_POSZ
- EK3_SRC2_VELXY
- EK3_SRC2_VELZ
- EK3_SRC2_YAW
- EK3_SRC3_POSXY
- EK3_SRC3_POSZ
- EK3_SRC3_VELXY
- EK3_SRC3_VELZ
- EK3_SRC3_YAW
- EK3_SRC_OPTIONS
- EK3_TAU_OUTPUT
- EK3_TERR_GRAD
- EK3_VELD_M_NSE
- EK3_VELNE_M_NSE
- EK3_VEL_I_GATE
- EK3_VIS_VERR_MAX
- EK3_VIS_VERR_MIN
- EK3_WENC_VERR
- EK3_WIND_PSCALE
- EK3_WIND_P_NSE
- EK3_YAW_I_GATE
- EK3_YAW_M_NSE
