name: gps
description: ArduPilot gps parameters
version: schema
schema_params:
- GPS1_CAN_NODEID
- GPS1_CAN_OVRIDE
- GPS1_COM_PORT
- GPS1_DELAY_MS
- GPS1_GNSS_MODE
- GPS1_MB_OFS_X
- GPS1_MB_OFS_Y
- GPS1_MB_OFS_Z
- GPS1_MB_TYPE
- GPS1_POS_X
- GPS1_POS_Y
- GPS1_POS_Z
- GPS1_RATE_MS
- GPS1_TYPE
- GPS2_CAN_NODEID
- GPS2_CAN_OVRIDE
- GPS2_COM_PORT
- GPS2_DELAY_MS
- GPS2_GNSS_MODE
- GPS2_MB_OFS_X
- GPS2_MB_OFS_Y
- GPS2_MB_OFS_Z
- GPS2_MB_TYPE
- GPS2_POS_X
- GPS2_POS_Y
- GPS2_POS_Z
- GPS2_RATE_MS
- GPS2_TYPE
- GPS_AUTO_CONFIG
- GPS_AUTO_SWITCH
- GPS_BLEND_MASK
- GPS_CAN_NODEID1
- GPS_CAN_NODEID2
- GPS_COM_PORT
- GPS_COM_PORT2
- GPS_DELAY_MS
- GPS_DELAY_MS2
- GPS_DRV_OPTIONS
- GPS_GNSS_MODE
- GPS_GNSS_MODE2
- GPS_INJECT_TO
- GPS_MB1_OFS_X
- GPS_MB1_OFS_Y
- GPS_MB1_OFS_Z
- GPS_MB1_TYPE
- GPS_MB2_OFS_X
- GPS_MB2_OFS_Y
- GPS_MB2_OFS_Z
- GPS_MB2_TYPE
- GPS_MIN_ELEV
- GPS_NAVFILTER
- GPS_POS1_X
- GPS_POS1_Y
- GPS_POS1_Z
- GPS_POS2_X
- GPS_POS2_Y
- GPS_POS2_Z
- GPS_PRIMARY
- GPS_RATE_MS
- GPS_RATE_MS2
- GPS_RAW_DATA
- GPS_SAVE_CFG
- GPS_SBAS_MODE
- GPS_SBP_LOGMASK
- GPS_TYPE
- GPS_TYPE2
