params:
  BTN_ENABLE: 0
  FRSKY_DNLINK1_ID: 20
  FRSKY_DNLINK2_ID: 7
  FRSKY_DNLINK_ID: 27
  FRSKY_OPTIONS: 0
  FRSKY_UPLINK_ID: 13
  NTF_BUZZ_ON_LVL: 1
  NTF_BUZZ_PIN: 32
  NTF_BUZZ_TYPES: 5
  NTF_BUZZ_VOLUME: 100
  NTF_DISPLAY_TYPE: 0
  NTF_LED_BRIGHT: 3
  NTF_LED_LEN: 1
  NTF_LED_OVERRIDE: 0
  NTF_LED_TYPES: 123079
