name: ahrs
description: ArduPilot ahrs parameters
version: schema
schema_params:
- AHRS_COMP_BETA
- AHRS_CUSTOM_PIT
- AHRS_CUSTOM_ROLL
- AHRS_CUSTOM_YAW
- AHRS_EKF_TYPE
- AHRS_GPS_GAIN
- AHRS_GPS_MINSATS
- AHRS_GPS_USE
- AHRS_OPTIONS
- AHRS_ORIENTATION
- AHRS_ORIGIN_ALT
- AHRS_ORIGIN_LAT
- AHRS_ORIGIN_LON
- AHRS_RP_P
- AHRS_TRIM_X
- AHRS_TRIM_Y
- AHRS_TRIM_Z
- AHRS_WIND_MAX
- AHRS_YAW_P
