params:
  FENCE_ACTION: 1
  FENCE_ALT_MAX: 100
  FENCE_ALT_MIN: -10
  FENCE_AUTOENABLE: 0
  FENCE_ENABLE: 0
  FENCE_MARGIN: 2
  FENCE_OPTIONS: 1
  FENCE_RADIUS: 300
  FENCE_RET_ALT: 0
  FENCE_RET_RALLY: 0
  FENCE_TOTAL: 0
  FENCE_TYPE: 4
