name: relay
description: ArduPilot relay parameters
version: schema
schema_params:
- RELAY10_DEFAULT
- RELAY10_FUNCTION
- RELAY10_INVERTED
- RELAY10_PIN
- RELAY11_DEFAULT
- RELAY11_FUNCTION
- RELAY11_INVERTED
- RELAY11_PIN
- RELAY12_DEFAULT
- RELAY12_FUNCTION
- RELAY12_INVERTED
- RELAY12_PIN
- RELAY13_DEFAULT
- RELAY13_FUNCTION
- RELAY13_INVERTED
- RELAY13_PIN
- RELAY14_DEFAULT
- RELAY14_FUNCTION
- RELAY14_INVERTED
- RELAY14_PIN
- RELAY15_DEFAULT
- RELAY15_FUNCTION
- RELAY15_INVERTED
- RELAY15_PIN
- RELAY16_DEFAULT
- RELAY16_FUNCTION
- RELAY16_INVERTED
- RELAY16_PIN
- RELAY1_DEFAULT
- RELAY1_FUNCTION
- RELAY1_INVERTED
- RELAY1_PIN
- RELAY2_DEFAULT
- RELAY2_FUNCTION
- RELAY2_INVERTED
- RELAY2_PIN
- RELAY3_DEFAULT
- RELAY3_FUNCTION
- RELAY3_INVERTED
- RELAY3_PIN
- RELAY4_DEFAULT
- RELAY4_FUNCTION
- RELAY4_INVERTED
- RELAY4_PIN
- RELAY5_DEFAULT
- RELAY5_FUNCTION
- RELAY5_INVERTED
- RELAY5_PIN
- RELAY6_DEFAULT
- RELAY6_FUNCTION
- RELAY6_INVERTED
- RELAY6_PIN
- RELAY7_DEFAULT
- RELAY7_FUNCTION
- RELAY7_INVERTED
- RELAY7_PIN
- RELAY8_DEFAULT
- RELAY8_FUNCTION
- RELAY8_INVERTED
- RELAY8_PIN
- RELAY9_DEFAULT
- RELAY9_FUNCTION
- RELAY9_INVERTED
- RELAY9_PIN
