params:
  LAND_ABORT_DEG: 0
  LAND_ABORT_THR: 0
  LAND_DISARMDELAY: 20
  LAND_FLAP_PERCNT: 0
  LAND_FLARE_AIM: 50
  LAND_FLARE_ALT: 3
  LAND_FLARE_SEC: 2
  LAND_OPTIONS: 0
  LAND_PF_ALT: 10
  LAND_PF_ARSPD: 0
  LAND_PF_SEC: 6
  LAND_PITCH_DEG: 0
  LAND_SLOPE_RCALC: 2
  LAND_THEN_NEUTRL: 0
  LAND_THR_SLEW: 0
  LAND_TYPE: 0
  LAND_WIND_COMP: 50
  TKOFF_ALT: 30
  TKOFF_DIST: 200
  TKOFF_GND_PITCH: 5
  TKOFF_LVL_ALT: 10
  TKOFF_LVL_PITCH: 15
