name: servo
description: ArduPilot servo parameters
version: schema
schema_params:
- SERVO10_FUNCTION
- SERVO10_MAX
- SERVO10_MIN
- SERVO10_REVERSED
- SERVO10_TRIM
- SERVO11_FUNCTION
- SERVO11_MAX
- SERVO11_MIN
- SERVO11_REVERSED
- SERVO11_TRIM
- SERVO12_FUNCTION
- SERVO12_MAX
- SERVO12_MIN
- SERVO12_REVERSED
- SERVO12_TRIM
- SERVO13_FUNCTION
- SERVO13_MAX
- SERVO13_MIN
- SERVO13_REVERSED
- SERVO13_TRIM
- SERVO14_FUNCTION
- SERVO14_MAX
- SERVO14_MIN
- SERVO14_REVERSED
- SERVO14_TRIM
- SERVO15_FUNCTION
- SERVO15_MAX
- SERVO15_MIN
- SERVO15_REVERSED
- SERVO15_TRIM
- SERVO16_FUNCTION
- SERVO16_MAX
- SERVO16_MIN
- SERVO16_REVERSED
- SERVO16_TRIM
- SERVO17_FUNCTION
- SERVO17_MAX
- SERVO17_MIN
- SERVO17_REVERSED
- SERVO17_TRIM
- SERVO18_FUNCTION
- SERVO18_MAX
- SERVO18_MIN
- SERVO18_REVERSED
- SERVO18_TRIM
- SERVO19_FUNCTION
- SERVO19_MAX
- SERVO19_MIN
- SERVO19_REVERSED
- SERVO19_TRIM
- SERVO1_FUNCTION
- SERVO1_MAX
- SERVO1_MIN
- SERVO1_REVERSED
- SERVO1_TRIM
- SERVO20_FUNCTION
- SERVO20_MAX
- SERVO20_MIN
- SERVO20_REVERSED
- SERVO20_TRIM
- SERVO21_FUNCTION
- SERVO21_MAX
- SERVO21_MIN
- SERVO21_REVERSED
- SERVO21_TRIM
- SERVO22_FUNCTION
- SERVO22_MAX
- SERVO22_MIN
- SERVO22_REVERSED
- SERVO22_TRIM
- SERVO23_FUNCTION
- SERVO23_MAX
- SERVO23_MIN
- SERVO23_REVERSED
- SERVO23_TRIM
- SERVO24_FUNCTION
- SERVO24_MAX
- SERVO24_MIN
- SERVO24_REVERSED
- SERVO24_TRIM
- SERVO25_FUNCTION
- SERVO25_MAX
- SERVO25_MIN
- SERVO25_REVERSED
- SERVO25_TRIM
- SERVO26_FUNCTION
- SERVO26_MAX
- SERVO26_MIN
- SERVO26_REVERSED
- SERVO26_TRIM
- SERVO27_FUNCTION
- SERVO27_MAX
- SERVO27_MIN
- SERVO27_REVERSED
- SERVO27_TRIM
- SERVO28_FUNCTION
- SERVO28_MAX
- SERVO28_MIN
- SERVO28_REVERSED
- SERVO28_TRIM
- SERVO29_FUNCTION
- SERVO29_MAX
- SERVO29_MIN
- SERVO29_REVERSED
- SERVO29_TRIM
- SERVO2_FUNCTION
- SERVO2_MAX
- SERVO2_MIN
- SERVO2_REVERSED
- SERVO2_TRIM
- SERVO30_FUNCTION
- SERVO30_MAX
- SERVO30_MIN
- SERVO30_REVERSED
- SERVO30_TRIM
- SERVO31_FUNCTION
- SERVO31_MAX
- SERVO31_MIN
- SERVO31_REVERSED
- SERVO31_TRIM
- SERVO32_FUNCTION
- SERVO32_MAX
- SERVO32_MIN
- SERVO32_REVERSED
- SERVO32_TRIM
- SERVO3_FUNCTION
- SERVO3_MAX
- SERVO3_MIN
- SERVO3_REVERSED
- SERVO3_TRIM
- SERVO4_FUNCTION
- SERVO4_MAX
- SERVO4_MIN
- SERVO4_REVERSED
- SERVO4_TRIM
- SERVO5_FUNCTION
- SERVO5_MAX
- SERVO5_MIN
- SERVO5_REVERSED
- SERVO5_TRIM
- SERVO6_FUNCTION
- SERVO6_MAX
- SERVO6_MIN
- SERVO6_REVERSED
- SERVO6_TRIM
- SERVO7_FUNCTION
- SERVO7_MAX
- SERVO7_MIN
- SERVO7_REVERSED
- SERVO7_TRIM
- SERVO8_FUNCTION
- SERVO8_MAX
- SERVO8_MIN
- SERVO8_REVERSED
- SERVO8_TRIM
- SERVO9_FUNCTION
- SERVO9_MAX
- SERVO9_MIN
- SERVO9_REVERSED
- SERVO9_TRIM
- SERVO_32_ENABLE
- SERVO_AUTO_TRIM
- SERVO_BLH_3DMASK
- SERVO_BLH_AUTO
- SERVO_BLH_BDMASK
- SERVO_BLH_DEBUG
- SERVO_BLH_MASK
- SERVO_BLH_OTYPE
- SERVO_BLH_POLES
- SERVO_BLH_PORT
- SERVO_BLH_RVMASK
- SERVO_BLH_TEST
- SERVO_BLH_TMOUT
- SERVO_BLH_TRATE
- SERVO_DSHOT_ESC
- SERVO_DSHOT_RATE
- SERVO_FTW_MASK
- SERVO_FTW_POLES
- SERVO_FTW_RVMASK
- SERVO_GPIO_MASK
- SERVO_RATE
- SERVO_RC_FS_MSK
- SERVO_ROB_POSMAX
- SERVO_ROB_POSMIN
- SERVO_SBUS_RATE
- SERVO_VOLZ_MASK
- SERVO_VOLZ_RANGE
