name: safety
description: ArduPilot safety parameters
version: schema
schema_params:
- ADSB_EMIT_TYPE
- ADSB_ICAO_ID
- ADSB_ICAO_SPECL
- ADSB_LEN_WIDTH
- ADSB_LIST_ALT
- ADSB_LIST_MAX
- ADSB_LIST_RADIUS
- ADSB_LOG
- ADSB_OFFSET_LAT
- ADSB_OFFSET_LON
- ADSB_OPTIONS
- ADSB_RF_CAPABLE
- ADSB_RF_SELECT
- ADSB_SQUAWK
- ADSB_TYPE
- AFS_AMSL_ERR_GPS
- AFS_AMSL_LIMIT
- AFS_DUAL_LOSS
- AFS_ENABLE
- AFS_GCS_TIMEOUT
- AFS_GEOFENCE
- AFS_HB_PIN
- AFS_MAN_PIN
- AFS_MAX_COM_LOSS
- AFS_MAX_GPS_LOSS
- AFS_MAX_RANGE
- AFS_OPTIONS
- AFS_QNH_PRESSURE
- AFS_RC
- AFS_RC_FAIL_TIME
- AFS_RC_MAN_ONLY
- AFS_TERMINATE
- AFS_TERM_ACTION
- AFS_TERM_PIN
- AFS_WP_COMMS
- AFS_WP_GPS_LOSS
- AVD_ENABLE
- AVD_F_ACTION
- AVD_F_ALT_MIN
- AVD_F_DIST_XY
- AVD_F_DIST_Z
- AVD_F_RCVRY
- AVD_F_TIME
- AVD_OBS_MAX
- AVD_W_ACTION
- AVD_W_DIST_XY
- AVD_W_DIST_Z
- AVD_W_TIME
