name: osd
description: ArduPilot osd parameters
version: schema
schema_params:
- OSD1_ACRVOLT_EN
- OSD1_ACRVOLT_X
- OSD1_ACRVOLT_Y
- OSD1_ALTITUDE_EN
- OSD1_ALTITUDE_X
- OSD1_ALTITUDE_Y
- OSD1_ARMING_EN
- OSD1_ARMING_X
- OSD1_ARMING_Y
- OSD1_ASPD1_EN
- OSD1_ASPD1_X
- OSD1_ASPD1_Y
- OSD1_ASPD2_EN
- OSD1_ASPD2_X
- OSD1_ASPD2_Y
- OSD1_ASPEED_EN
- OSD1_ASPEED_X
- OSD1_ASPEED_Y
- OSD1_ATEMP_EN
- OSD1_ATEMP_X
- OSD1_ATEMP_Y
- OSD1_AVGCELLV_EN
- OSD1_AVGCELLV_X
- OSD1_AVGCELLV_Y
- OSD1_BAT2USED_EN
- OSD1_BAT2USED_X
- OSD1_BAT2USED_Y
- OSD1_BAT2_VLT_EN
- OSD1_BAT2_VLT_X
- OSD1_BAT2_VLT_Y
- OSD1_BATTBAR_EN
- OSD1_BATTBAR_X
- OSD1_BATTBAR_Y
- OSD1_BATUSED_EN
- OSD1_BATUSED_X
- OSD1_BATUSED_Y
- OSD1_BAT_VOLT_EN
- OSD1_BAT_VOLT_X
- OSD1_BAT_VOLT_Y
- OSD1_BTEMP_EN
- OSD1_BTEMP_X
- OSD1_BTEMP_Y
- OSD1_CALLSIGN_EN
- OSD1_CALLSIGN_X
- OSD1_CALLSIGN_Y
- OSD1_CELLVOLT_EN
- OSD1_CELLVOLT_X
- OSD1_CELLVOLT_Y
- OSD1_CHAN_MAX
- OSD1_CHAN_MIN
- OSD1_CLIMBEFF_EN
- OSD1_CLIMBEFF_X
- OSD1_CLIMBEFF_Y
- OSD1_CLK_EN
- OSD1_CLK_X
- OSD1_CLK_Y
- OSD1_COMPASS_EN
- OSD1_COMPASS_X
- OSD1_COMPASS_Y
- OSD1_CRSSHAIR_EN
- OSD1_CRSSHAIR_X
- OSD1_CRSSHAIR_Y
- OSD1_CURRENT2_EN
- OSD1_CURRENT2_X
- OSD1_CURRENT2_Y
- OSD1_CURRENT_EN
- OSD1_CURRENT_X
- OSD1_CURRENT_Y
- OSD1_DIST_EN
- OSD1_DIST_X
- OSD1_DIST_Y
- OSD1_EFF_EN
- OSD1_EFF_X
- OSD1_EFF_Y
- OSD1_ENABLE
- OSD1_ESCAMPS_EN
- OSD1_ESCAMPS_X
- OSD1_ESCAMPS_Y
- OSD1_ESCRPM_EN
- OSD1_ESCRPM_X
- OSD1_ESCRPM_Y
- OSD1_ESCTEMP_EN
- OSD1_ESCTEMP_X
- OSD1_ESCTEMP_Y
- OSD1_ESC_IDX
- OSD1_FENCE_EN
- OSD1_FENCE_X
- OSD1_FENCE_Y
- OSD1_FLTIME_EN
- OSD1_FLTIME_X
- OSD1_FLTIME_Y
- OSD1_FLTMODE_EN
- OSD1_FLTMODE_X
- OSD1_FLTMODE_Y
- OSD1_FONT
- OSD1_GPSLAT_EN
- OSD1_GPSLAT_X
- OSD1_GPSLAT_Y
- OSD1_GPSLONG_EN
- OSD1_GPSLONG_X
- OSD1_GPSLONG_Y
- OSD1_GSPEED_EN
- OSD1_GSPEED_X
- OSD1_GSPEED_Y
- OSD1_HDOP_EN
- OSD1_HDOP_X
- OSD1_HDOP_Y
- OSD1_HEADING_EN
- OSD1_HEADING_X
- OSD1_HEADING_Y
- OSD1_HOMEDIR_EN
- OSD1_HOMEDIR_X
- OSD1_HOMEDIR_Y
- OSD1_HOMEDIST_EN
- OSD1_HOMEDIST_X
- OSD1_HOMEDIST_Y
- OSD1_HOME_EN
- OSD1_HOME_X
- OSD1_HOME_Y
- OSD1_HORIZON_EN
- OSD1_HORIZON_X
- OSD1_HORIZON_Y
- OSD1_LINK_Q_EN
- OSD1_LINK_Q_X
- OSD1_LINK_Q_Y
- OSD1_MESSAGE_EN
- OSD1_MESSAGE_X
- OSD1_MESSAGE_Y
- OSD1_PITCH_EN
- OSD1_PITCH_X
- OSD1_PITCH_Y
- OSD1_PLUSCODE_EN
- OSD1_PLUSCODE_X
- OSD1_PLUSCODE_Y
- OSD1_POWER_EN
- OSD1_POWER_X
- OSD1_POWER_Y
- OSD1_RC_ANT_EN
- OSD1_RC_ANT_X
- OSD1_RC_ANT_Y
- OSD1_RC_LQ_EN
- OSD1_RC_LQ_X
- OSD1_RC_LQ_Y
- OSD1_RC_PWR_EN
- OSD1_RC_PWR_X
- OSD1_RC_PWR_Y
- OSD1_RC_SNR_EN
- OSD1_RC_SNR_X
- OSD1_RC_SNR_Y
- OSD1_RESTVOLT_EN
- OSD1_RESTVOLT_X
- OSD1_RESTVOLT_Y
- OSD1_RNGF_EN
- OSD1_RNGF_X
- OSD1_RNGF_Y
- OSD1_ROLL_EN
- OSD1_ROLL_X
- OSD1_ROLL_Y
- OSD1_RPM_EN
- OSD1_RPM_X
- OSD1_RPM_Y
- OSD1_RSSIDBM_EN
- OSD1_RSSIDBM_X
- OSD1_RSSIDBM_Y
- OSD1_RSSI_EN
- OSD1_RSSI_X
- OSD1_RSSI_Y
- OSD1_SATS_EN
- OSD1_SATS_X
- OSD1_SATS_Y
- OSD1_SIDEBARS_EN
- OSD1_SIDEBARS_X
- OSD1_SIDEBARS_Y
- OSD1_STATS_EN
- OSD1_STATS_X
- OSD1_STATS_Y
- OSD1_TEMP_EN
- OSD1_TEMP_X
- OSD1_TEMP_Y
- OSD1_TER_HGT_EN
- OSD1_TER_HGT_X
- OSD1_TER_HGT_Y
- OSD1_THROTTLE_EN
- OSD1_THROTTLE_X
- OSD1_THROTTLE_Y
- OSD1_TXT_RES
- OSD1_VSPEED_EN
- OSD1_VSPEED_X
- OSD1_VSPEED_Y
- OSD1_VTX_PWR_EN
- OSD1_VTX_PWR_X
- OSD1_VTX_PWR_Y
- OSD1_WAYPOINT_EN
- OSD1_WAYPOINT_X
- OSD1_WAYPOINT_Y
- OSD1_WIND_EN
- OSD1_WIND_X
- OSD1_WIND_Y
- OSD1_XTRACK_EN
- OSD1_XTRACK_X
- OSD1_XTRACK_Y
- OSD2_ACRVOLT_EN
- OSD2_ACRVOLT_X
- OSD2_ACRVOLT_Y
- OSD2_ALTITUDE_EN
- OSD2_ALTITUDE_X
- OSD2_ALTITUDE_Y
- OSD2_ARMING_EN
- OSD2_ARMING_X
- OSD2_ARMING_Y
- OSD2_ASPD1_EN
- OSD2_ASPD1_X
- OSD2_ASPD1_Y
- OSD2_ASPD2_EN
- OSD2_ASPD2_X
- OSD2_ASPD2_Y
- OSD2_ASPEED_EN
- OSD2_ASPEED_X
- OSD2_ASPEED_Y
- OSD2_ATEMP_EN
- OSD2_ATEMP_X
- OSD2_ATEMP_Y
- OSD2_AVGCELLV_EN
- OSD2_AVGCELLV_X
- OSD2_AVGCELLV_Y
- OSD2_BAT2USED_EN
- OSD2_BAT2USED_X
- OSD2_BAT2USED_Y
- OSD2_BAT2_VLT_EN
- OSD2_BAT2_VLT_X
- OSD2_BAT2_VLT_Y
- OSD2_BATTBAR_EN
- OSD2_BATTBAR_X
- OSD2_BATTBAR_Y
- OSD2_BATUSED_EN
- OSD2_BATUSED_X
- OSD2_BATUSED_Y
- OSD2_BAT_VOLT_EN
- OSD2_BAT_VOLT_X
- OSD2_BAT_VOLT_Y
- OSD2_BTEMP_EN
- OSD2_BTEMP_X
- OSD2_BTEMP_Y
- OSD2_CALLSIGN_EN
- OSD2_CALLSIGN_X
- OSD2_CALLSIGN_Y
- OSD2_CELLVOLT_EN
- OSD2_CELLVOLT_X
- OSD2_CELLVOLT_Y
- OSD2_CHAN_MAX
- OSD2_CHAN_MIN
- OSD2_CLIMBEFF_EN
- OSD2_CLIMBEFF_X
- OSD2_CLIMBEFF_Y
- OSD2_CLK_EN
- OSD2_CLK_X
- OSD2_CLK_Y
- OSD2_COMPASS_EN
- OSD2_COMPASS_X
- OSD2_COMPASS_Y
- OSD2_CRSSHAIR_EN
- OSD2_CRSSHAIR_X
- OSD2_CRSSHAIR_Y
- OSD2_CURRENT2_EN
- OSD2_CURRENT2_X
- OSD2_CURRENT2_Y
- OSD2_CURRENT_EN
- OSD2_CURRENT_X
- OSD2_CURRENT_Y
- OSD2_DIST_EN
- OSD2_DIST_X
- OSD2_DIST_Y
- OSD2_EFF_EN
- OSD2_EFF_X
- OSD2_EFF_Y
- OSD2_ENABLE
- OSD2_ESCAMPS_EN
- OSD2_ESCAMPS_X
- OSD2_ESCAMPS_Y
- OSD2_ESCRPM_EN
- OSD2_ESCRPM_X
- OSD2_ESCRPM_Y
- OSD2_ESCTEMP_EN
- OSD2_ESCTEMP_X
- OSD2_ESCTEMP_Y
- OSD2_ESC_IDX
- OSD2_FENCE_EN
- OSD2_FENCE_X
- OSD2_FENCE_Y
- OSD2_FLTIME_EN
- OSD2_FLTIME_X
- OSD2_FLTIME_Y
- OSD2_FLTMODE_EN
- OSD2_FLTMODE_X
- OSD2_FLTMODE_Y
- OSD2_FONT
- OSD2_GPSLAT_EN
- OSD2_GPSLAT_X
- OSD2_GPSLAT_Y
- OSD2_GPSLONG_EN
- OSD2_GPSLONG_X
- OSD2_GPSLONG_Y
- OSD2_GSPEED_EN
- OSD2_GSPEED_X
- OSD2_GSPEED_Y
- OSD2_HDOP_EN
- OSD2_HDOP_X
- OSD2_HDOP_Y
- OSD2_HEADING_EN
- OSD2_HEADING_X
- OSD2_HEADING_Y
- OSD2_HOMEDIR_EN
- OSD2_HOMEDIR_X
- OSD2_HOMEDIR_Y
- OSD2_HOMEDIST_EN
- OSD2_HOMEDIST_X
- OSD2_HOMEDIST_Y
- OSD2_HOME_EN
- OSD2_HOME_X
- OSD2_HOME_Y
- OSD2_HORIZON_EN
- OSD2_HORIZON_X
- OSD2_HORIZON_Y
- OSD2_LINK_Q_EN
- OSD2_LINK_Q_X
- OSD2_LINK_Q_Y
- OSD2_MESSAGE_EN
- OSD2_MESSAGE_X
- OSD2_MESSAGE_Y
- OSD2_PITCH_EN
- OSD2_PITCH_X
- OSD2_PITCH_Y
- OSD2_PLUSCODE_EN
- OSD2_PLUSCODE_X
- OSD2_PLUSCODE_Y
- OSD2_POWER_EN
- OSD2_POWER_X
- OSD2_POWER_Y
- OSD2_RC_ANT_EN
- OSD2_RC_ANT_X
- OSD2_RC_ANT_Y
- OSD2_RC_LQ_EN
- OSD2_RC_LQ_X
- OSD2_RC_LQ_Y
- OSD2_RC_PWR_EN
- OSD2_RC_PWR_X
- OSD2_RC_PWR_Y
- OSD2_RC_SNR_EN
- OSD2_RC_SNR_X
- OSD2_RC_SNR_Y
- OSD2_RESTVOLT_EN
- OSD2_RESTVOLT_X
- OSD2_RESTVOLT_Y
- OSD2_RNGF_EN
- OSD2_RNGF_X
- OSD2_RNGF_Y
- OSD2_ROLL_EN
- OSD2_ROLL_X
- OSD2_ROLL_Y
- OSD2_RPM_EN
- OSD2_RPM_X
- OSD2_RPM_Y
- OSD2_RSSIDBM_EN
- OSD2_RSSIDBM_X
- OSD2_RSSIDBM_Y
- OSD2_RSSI_EN
- OSD2_RSSI_X
- OSD2_RSSI_Y
- OSD2_SATS_EN
- OSD2_SATS_X
- OSD2_SATS_Y
- OSD2_SIDEBARS_EN
- OSD2_SIDEBARS_X
- OSD2_SIDEBARS_Y
- OSD2_STATS_EN
- OSD2_STATS_X
- OSD2_STATS_Y
- OSD2_TEMP_EN
- OSD2_TEMP_X
- OSD2_TEMP_Y
- OSD2_TER_HGT_EN
- OSD2_TER_HGT_X
- OSD2_TER_HGT_Y
- OSD2_THROTTLE_EN
- OSD2_THROTTLE_X
- OSD2_THROTTLE_Y
- OSD2_TXT_RES
- OSD2_VSPEED_EN
- OSD2_VSPEED_X
- OSD2_VSPEED_Y
- OSD2_VTX_PWR_EN
- OSD2_VTX_PWR_X
- OSD2_VTX_PWR_Y
- OSD2_WAYPOINT_EN
- OSD2_WAYPOINT_X
- OSD2_WAYPOINT_Y
- OSD2_WIND_EN
- OSD2_WIND_X
- OSD2_WIND_Y
- OSD2_XTRACK_EN
- OSD2_XTRACK_X
- OSD2_XTRACK_Y
- OSD3_ACRVOLT_EN
- OSD3_ACRVOLT_X
- OSD3_ACRVOLT_Y
- OSD3_ALTITUDE_EN
- OSD3_ALTITUDE_X
- OSD3_ALTITUDE_Y
- OSD3_ARMING_EN
- OSD3_ARMING_X
- OSD3_ARMING_Y
- OSD3_ASPD1_EN
- OSD3_ASPD1_X
- OSD3_ASPD1_Y
- OSD3_ASPD2_EN
- OSD3_ASPD2_X
- OSD3_ASPD2_Y
- OSD3_ASPEED_EN
- OSD3_ASPEED_X
- OSD3_ASPEED_Y
- OSD3_ATEMP_EN
- OSD3_ATEMP_X
- OSD3_ATEMP_Y
- OSD3_AVGCELLV_EN
- OSD3_AVGCELLV_X
- OSD3_AVGCELLV_Y
- OSD3_BAT2USED_EN
- OSD3_BAT2USED_X
- OSD3_BAT2USED_Y
- OSD3_BAT2_VLT_EN
- OSD3_BAT2_VLT_X
- OSD3_BAT2_VLT_Y
- OSD3_BATTBAR_EN
- OSD3_BATTBAR_X
- OSD3_BATTBAR_Y
- OSD3_BATUSED_EN
- OSD3_BATUSED_X
- OSD3_BATUSED_Y
- OSD3_BAT_VOLT_EN
- OSD3_BAT_VOLT_X
- OSD3_BAT_VOLT_Y
- OSD3_BTEMP_EN
- OSD3_BTEMP_X
- OSD3_BTEMP_Y
- OSD3_CALLSIGN_EN
- OSD3_CALLSIGN_X
- OSD3_CALLSIGN_Y
- OSD3_CELLVOLT_EN
- OSD3_CELLVOLT_X
- OSD3_CELLVOLT_Y
- OSD3_CHAN_MAX
- OSD3_CHAN_MIN
- OSD3_CLIMBEFF_EN
- OSD3_CLIMBEFF_X
- OSD3_CLIMBEFF_Y
- OSD3_CLK_EN
- OSD3_CLK_X
- OSD3_CLK_Y
- OSD3_COMPASS_EN
- OSD3_COMPASS_X
- OSD3_COMPASS_Y
- OSD3_CRSSHAIR_EN
- OSD3_CRSSHAIR_X
- OSD3_CRSSHAIR_Y
- OSD3_CURRENT2_EN
- OSD3_CURRENT2_X
- OSD3_CURRENT2_Y
- OSD3_CURRENT_EN
- OSD3_CURRENT_X
- OSD3_CURRENT_Y
- OSD3_DIST_EN
- OSD3_DIST_X
- OSD3_DIST_Y
- OSD3_EFF_EN
- OSD3_EFF_X
- OSD3_EFF_Y
- OSD3_ENABLE
- OSD3_ESCAMPS_EN
- OSD3_ESCAMPS_X
- OSD3_ESCAMPS_Y
- OSD3_ESCRPM_EN
- OSD3_ESCRPM_X
- OSD3_ESCRPM_Y
- OSD3_ESCTEMP_EN
- OSD3_ESCTEMP_X
- OSD3_ESCTEMP_Y
- OSD3_ESC_IDX
- OSD3_FENCE_EN
- OSD3_FENCE_X
- OSD3_FENCE_Y
- OSD3_FLTIME_EN
- OSD3_FLTIME_X
- OSD3_FLTIME_Y
- OSD3_FLTMODE_EN
- OSD3_FLTMODE_X
- OSD3_FLTMODE_Y
- OSD3_FONT
- OSD3_GPSLAT_EN
- OSD3_GPSLAT_X
- OSD3_GPSLAT_Y
- OSD3_GPSLONG_EN
- OSD3_GPSLONG_X
- OSD3_GPSLONG_Y
- OSD3_GSPEED_EN
- OSD3_GSPEED_X
- OSD3_GSPEED_Y
- OSD3_HDOP_EN
- OSD3_HDOP_X
- OSD3_HDOP_Y
- OSD3_HEADING_EN
- OSD3_HEADING_X
- OSD3_HEADING_Y
- OSD3_HOMEDIR_EN
- OSD3_HOMEDIR_X
- OSD3_HOMEDIR_Y
- OSD3_HOMEDIST_EN
- OSD3_HOMEDIST_X
- OSD3_HOMEDIST_Y
- OSD3_HOME_EN
- OSD3_HOME_X
- OSD3_HOME_Y
- OSD3_HORIZON_EN
- OSD3_HORIZON_X
- OSD3_HORIZON_Y
- OSD3_LINK_Q_EN
- OSD3_LINK_Q_X
- OSD3_LINK_Q_Y
- OSD3_MESSAGE_EN
- OSD3_MESSAGE_X
- OSD3_MESSAGE_Y
- OSD3_PITCH_EN
- OSD3_PITCH_X
- OSD3_PITCH_Y
- OSD3_PLUSCODE_EN
- OSD3_PLUSCODE_X
- OSD3_PLUSCODE_Y
- OSD3_POWER_EN
- OSD3_POWER_X
- OSD3_POWER_Y
- OSD3_RC_ANT_EN
- OSD3_RC_ANT_X
- OSD3_RC_ANT_Y
- OSD3_RC_LQ_EN
- OSD3_RC_LQ_X
- OSD3_RC_LQ_Y
- OSD3_RC_PWR_EN
- OSD3_RC_PWR_X
- OSD3_RC_PWR_Y
- OSD3_RC_SNR_EN
- OSD3_RC_SNR_X
- OSD3_RC_SNR_Y
- OSD3_RESTVOLT_EN
- OSD3_RESTVOLT_X
- OSD3_RESTVOLT_Y
- OSD3_RNGF_EN
- OSD3_RNGF_X
- OSD3_RNGF_Y
- OSD3_ROLL_EN
- OSD3_ROLL_X
- OSD3_ROLL_Y
- OSD3_RPM_EN
- OSD3_RPM_X
- OSD3_RPM_Y
- OSD3_RSSIDBM_EN
- OSD3_RSSIDBM_X
- OSD3_RSSIDBM_Y
- OSD3_RSSI_EN
- OSD3_RSSI_X
- OSD3_RSSI_Y
- OSD3_SATS_EN
- OSD3_SATS_X
- OSD3_SATS_Y
- OSD3_SIDEBARS_EN
- OSD3_SIDEBARS_X
- OSD3_SIDEBARS_Y
- OSD3_STATS_EN
- OSD3_STATS_X
- OSD3_STATS_Y
- OSD3_TEMP_EN
- OSD3_TEMP_X
- OSD3_TEMP_Y
- OSD3_TER_HGT_EN
- OSD3_TER_HGT_X
- OSD3_TER_HGT_Y
- OSD3_THROTTLE_EN
- OSD3_THROTTLE_X
- OSD3_THROTTLE_Y
- OSD3_TXT_RES
- OSD3_VSPEED_EN
- OSD3_VSPEED_X
- OSD3_VSPEED_Y
- OSD3_VTX_PWR_EN
- OSD3_VTX_PWR_X
- OSD3_VTX_PWR_Y
- OSD3_WAYPOINT_EN
- OSD3_WAYPOINT_X
- OSD3_WAYPOINT_Y
- OSD3_WIND_EN
- OSD3_WIND_X
- OSD3_WIND_Y
- OSD3_XTRACK_EN
- OSD3_XTRACK_X
- OSD3_XTRACK_Y
- OSD4_ACRVOLT_EN
- OSD4_ACRVOLT_X
- OSD4_ACRVOLT_Y
- OSD4_ALTITUDE_EN
- OSD4_ALTITUDE_X
- OSD4_ALTITUDE_Y
- OSD4_ARMING_EN
- OSD4_ARMING_X
- OSD4_ARMING_Y
- OSD4_ASPD1_EN
- OSD4_ASPD1_X
- OSD4_ASPD1_Y
- OSD4_ASPD2_EN
- OSD4_ASPD2_X
- OSD4_ASPD2_Y
- OSD4_ASPEED_EN
- OSD4_ASPEED_X
- OSD4_ASPEED_Y
- OSD4_ATEMP_EN
- OSD4_ATEMP_X
- OSD4_ATEMP_Y
- OSD4_AVGCELLV_EN
- OSD4_AVGCELLV_X
- OSD4_AVGCELLV_Y
- OSD4_BAT2USED_EN
- OSD4_BAT2USED_X
- OSD4_BAT2USED_Y
- OSD4_BAT2_VLT_EN
- OSD4_BAT2_VLT_X
- OSD4_BAT2_VLT_Y
- OSD4_BATTBAR_EN
- OSD4_BATTBAR_X
- OSD4_BATTBAR_Y
- OSD4_BATUSED_EN
- OSD4_BATUSED_X
- OSD4_BATUSED_Y
- OSD4_BAT_VOLT_EN
- OSD4_BAT_VOLT_X
- OSD4_BAT_VOLT_Y
- OSD4_BTEMP_EN
- OSD4_BTEMP_X
- OSD4_BTEMP_Y
- OSD4_CALLSIGN_EN
- OSD4_CALLSIGN_X
- OSD4_CALLSIGN_Y
- OSD4_CELLVOLT_EN
- OSD4_CELLVOLT_X
- OSD4_CELLVOLT_Y
- OSD4_CHAN_MAX
- OSD4_CHAN_MIN
- OSD4_CLIMBEFF_EN
- OSD4_CLIMBEFF_X
- OSD4_CLIMBEFF_Y
- OSD4_CLK_EN
- OSD4_CLK_X
- OSD4_CLK_Y
- OSD4_COMPASS_EN
- OSD4_COMPASS_X
- OSD4_COMPASS_Y
- OSD4_CRSSHAIR_EN
- OSD4_CRSSHAIR_X
- OSD4_CRSSHAIR_Y
- OSD4_CURRENT2_EN
- OSD4_CURRENT2_X
- OSD4_CURRENT2_Y
- OSD4_CURRENT_EN
- OSD4_CURRENT_X
- OSD4_CURRENT_Y
- OSD4_DIST_EN
- OSD4_DIST_X
- OSD4_DIST_Y
- OSD4_EFF_EN
- OSD4_EFF_X
- OSD4_EFF_Y
- OSD4_ENABLE
- OSD4_ESCAMPS_EN
- OSD4_ESCAMPS_X
- OSD4_ESCAMPS_Y
- OSD4_ESCRPM_EN
- OSD4_ESCRPM_X
- OSD4_ESCRPM_Y
- OSD4_ESCTEMP_EN
- OSD4_ESCTEMP_X
- OSD4_ESCTEMP_Y
- OSD4_ESC_IDX
- OSD4_FENCE_EN
- OSD4_FENCE_X
- OSD4_FENCE_Y
- OSD4_FLTIME_EN
- OSD4_FLTIME_X
- OSD4_FLTIME_Y
- OSD4_FLTMODE_EN
- OSD4_FLTMODE_X
- OSD4_FLTMODE_Y
- OSD4_FONT
- OSD4_GPSLAT_EN
- OSD4_GPSLAT_X
- OSD4_GPSLAT_Y
- OSD4_GPSLONG_EN
- OSD4_GPSLONG_X
- OSD4_GPSLONG_Y
- OSD4_GSPEED_EN
- OSD4_GSPEED_X
- OSD4_GSPEED_Y
- OSD4_HDOP_EN
- OSD4_HDOP_X
- OSD4_HDOP_Y
- OSD4_HEADING_EN
- OSD4_HEADING_X
- OSD4_HEADING_Y
- OSD4_HOMEDIR_EN
- OSD4_HOMEDIR_X
- OSD4_HOMEDIR_Y
- OSD4_HOMEDIST_EN
- OSD4_HOMEDIST_X
- OSD4_HOMEDIST_Y
- OSD4_HOME_EN
- OSD4_HOME_X
- OSD4_HOME_Y
- OSD4_HORIZON_EN
- OSD4_HORIZON_X
- OSD4_HORIZON_Y
- OSD4_LINK_Q_EN
- OSD4_LINK_Q_X
- OSD4_LINK_Q_Y
- OSD4_MESSAGE_EN
- OSD4_MESSAGE_X
- OSD4_MESSAGE_Y
- OSD4_PITCH_EN
- OSD4_PITCH_X
- OSD4_PITCH_Y
- OSD4_PLUSCODE_EN
- OSD4_PLUSCODE_X
- OSD4_PLUSCODE_Y
- OSD4_POWER_EN
- OSD4_POWER_X
- OSD4_POWER_Y
- OSD4_RC_ANT_EN
- OSD4_RC_ANT_X
- OSD4_RC_ANT_Y
- OSD4_RC_LQ_EN
- OSD4_RC_LQ_X
- OSD4_RC_LQ_Y
- OSD4_RC_PWR_EN
- OSD4_RC_PWR_X
- OSD4_RC_PWR_Y
- OSD4_RC_SNR_EN
- OSD4_RC_SNR_X
- OSD4_RC_SNR_Y
- OSD4_RESTVOLT_EN
- OSD4_RESTVOLT_X
- OSD4_RESTVOLT_Y
- OSD4_RNGF_EN
- OSD4_RNGF_X
- OSD4_RNGF_Y
- OSD4_ROLL_EN
- OSD4_ROLL_X
- OSD4_ROLL_Y
- OSD4_RPM_EN
- OSD4_RPM_X
- OSD4_RPM_Y
- OSD4_RSSIDBM_EN
- OSD4_RSSIDBM_X
- OSD4_RSSIDBM_Y
- OSD4_RSSI_EN
- OSD4_RSSI_X
- OSD4_RSSI_Y
- OSD4_SATS_EN
- OSD4_SATS_X
- OSD4_SATS_Y
- OSD4_SIDEBARS_EN
- OSD4_SIDEBARS_X
- OSD4_SIDEBARS_Y
- OSD4_STATS_EN
- OSD4_STATS_X
- OSD4_STATS_Y
- OSD4_TEMP_EN
- OSD4_TEMP_X
- OSD4_TEMP_Y
- OSD4_TER_HGT_EN
- OSD4_TER_HGT_X
- OSD4_TER_HGT_Y
- OSD4_THROTTLE_EN
- OSD4_THROTTLE_X
- OSD4_THROTTLE_Y
- OSD4_TXT_RES
- OSD4_VSPEED_EN
- OSD4_VSPEED_X
- OSD4_VSPEED_Y
- OSD4_VTX_PWR_EN
- OSD4_VTX_PWR_X
- OSD4_VTX_PWR_Y
- OSD4_WAYPOINT_EN
- OSD4_WAYPOINT_X
- OSD4_WAYPOINT_Y
- OSD4_WIND_EN
- OSD4_WIND_X
- OSD4_WIND_Y
- OSD4_XTRACK_EN
- OSD4_XTRACK_X
- OSD4_XTRACK_Y
- OSD5_CHAN_MAX
- OSD5_CHAN_MIN
- OSD5_ENABLE
- OSD5_PARAM1_EN
- OSD5_PARAM1_GRP
- OSD5_PARAM1_IDX
- OSD5_PARAM1_INCR
- OSD5_PARAM1_KEY
- OSD5_PARAM1_MAX
- OSD5_PARAM1_MIN
- OSD5_PARAM1_TYPE
- OSD5_PARAM1_X
- OSD5_PARAM1_Y
- OSD5_PARAM2_EN
- OSD5_PARAM2_GRP
- OSD5_PARAM2_IDX
- OSD5_PARAM2_INCR
- OSD5_PARAM2_KEY
- OSD5_PARAM2_MAX
- OSD5_PARAM2_MIN
- OSD5_PARAM2_TYPE
- OSD5_PARAM2_X
- OSD5_PARAM2_Y
- OSD5_PARAM3_EN
- OSD5_PARAM3_GRP
- OSD5_PARAM3_IDX
- OSD5_PARAM3_INCR
- OSD5_PARAM3_KEY
- OSD5_PARAM3_MAX
- OSD5_PARAM3_MIN
- OSD5_PARAM3_TYPE
- OSD5_PARAM3_X
- OSD5_PARAM3_Y
- OSD5_PARAM4_EN
- OSD5_PARAM4_GRP
- OSD5_PARAM4_IDX
- OSD5_PARAM4_INCR
- OSD5_PARAM4_KEY
- OSD5_PARAM4_MAX
- OSD5_PARAM4_MIN
- OSD5_PARAM4_TYPE
- OSD5_PARAM4_X
- OSD5_PARAM4_Y
- OSD5_PARAM5_EN
- OSD5_PARAM5_GRP
- OSD5_PARAM5_IDX
- OSD5_PARAM5_INCR
- OSD5_PARAM5_KEY
- OSD5_PARAM5_MAX
- OSD5_PARAM5_MIN
- OSD5_PARAM5_TYPE
- OSD5_PARAM5_X
- OSD5_PARAM5_Y
- OSD5_PARAM6_EN
- OSD5_PARAM6_GRP
- OSD5_PARAM6_IDX
- OSD5_PARAM6_INCR
- OSD5_PARAM6_KEY
- OSD5_PARAM6_MAX
- OSD5_PARAM6_MIN
- OSD5_PARAM6_TYPE
- OSD5_PARAM6_X
- OSD5_PARAM6_Y
- OSD5_PARAM7_EN
- OSD5_PARAM7_GRP
- OSD5_PARAM7_IDX
- OSD5_PARAM7_INCR
- OSD5_PARAM7_KEY
- OSD5_PARAM7_MAX
- OSD5_PARAM7_MIN
- OSD5_PARAM7_TYPE
- OSD5_PARAM7_X
- OSD5_PARAM7_Y
- OSD5_PARAM8_EN
- OSD5_PARAM8_GRP
- OSD5_PARAM8_IDX
- OSD5_PARAM8_INCR
- OSD5_PARAM8_KEY
- OSD5_PARAM8_MAX
- OSD5_PARAM8_MIN
- OSD5_PARAM8_TYPE
- OSD5_PARAM8_X
- OSD5_PARAM8_Y
- OSD5_PARAM9_EN
- OSD5_PARAM9_GRP
- OSD5_PARAM9_IDX
- OSD5_PARAM9_INCR
- OSD5_PARAM9_KEY
- OSD5_PARAM9_MAX
- OSD5_PARAM9_MIN
- OSD5_PARAM9_TYPE
- OSD5_PARAM9_X
- OSD5_PARAM9_Y
- OSD5_SAVE_X
- OSD5_SAVE_Y
- OSD6_CHAN_MAX
- OSD6_CHAN_MIN
- OSD6_ENABLE
- OSD6_PARAM1_EN
- OSD6_PARAM1_GRP
- OSD6_PARAM1_IDX
- OSD6_PARAM1_INCR
- OSD6_PARAM1_KEY
- OSD6_PARAM1_MAX
- OSD6_PARAM1_MIN
- OSD6_PARAM1_TYPE
- OSD6_PARAM1_X
- OSD6_PARAM1_Y
- OSD6_PARAM2_EN
- OSD6_PARAM2_GRP
- OSD6_PARAM2_IDX
- OSD6_PARAM2_INCR
- OSD6_PARAM2_KEY
- OSD6_PARAM2_MAX
- OSD6_PARAM2_MIN
- OSD6_PARAM2_TYPE
- OSD6_PARAM2_X
- OSD6_PARAM2_Y
- OSD6_PARAM3_EN
- OSD6_PARAM3_GRP
- OSD6_PARAM3_IDX
- OSD6_PARAM3_INCR
- OSD6_PARAM3_KEY
- OSD6_PARAM3_MAX
- OSD6_PARAM3_MIN
- OSD6_PARAM3_TYPE
- OSD6_PARAM3_X
- OSD6_PARAM3_Y
- OSD6_PARAM4_EN
- OSD6_PARAM4_GRP
- OSD6_PARAM4_IDX
- OSD6_PARAM4_INCR
- OSD6_PARAM4_KEY
- OSD6_PARAM4_MAX
- OSD6_PARAM4_MIN
- OSD6_PARAM4_TYPE
- OSD6_PARAM4_X
- OSD6_PARAM4_Y
- OSD6_PARAM5_EN
- OSD6_PARAM5_GRP
- OSD6_PARAM5_IDX
- OSD6_PARAM5_INCR
- OSD6_PARAM5_KEY
- OSD6_PARAM5_MAX
- OSD6_PARAM5_MIN
- OSD6_PARAM5_TYPE
- OSD6_PARAM5_X
- OSD6_PARAM5_Y
- OSD6_PARAM6_EN
- OSD6_PARAM6_GRP
- OSD6_PARAM6_IDX
- OSD6_PARAM6_INCR
- OSD6_PARAM6_KEY
- OSD6_PARAM6_MAX
- OSD6_PARAM6_MIN
- OSD6_PARAM6_TYPE
- OSD6_PARAM6_X
- OSD6_PARAM6_Y
- OSD6_PARAM7_EN
- OSD6_PARAM7_GRP
- OSD6_PARAM7_IDX
- OSD6_PARAM7_INCR
- OSD6_PARAM7_KEY
- OSD6_PARAM7_MAX
- OSD6_PARAM7_MIN
- OSD6_PARAM7_TYPE
- OSD6_PARAM7_X
- OSD6_PARAM7_Y
- OSD6_PARAM8_EN
- OSD6_PARAM8_GRP
- OSD6_PARAM8_IDX
- OSD6_PARAM8_INCR
- OSD6_PARAM8_KEY
- OSD6_PARAM8_MAX
- OSD6_PARAM8_MIN
- OSD6_PARAM8_TYPE
- OSD6_PARAM8_X
- OSD6_PARAM8_Y
- OSD6_PARAM9_EN
- OSD6_PARAM9_GRP
- OSD6_PARAM9_IDX
- OSD6_PARAM9_INCR
- OSD6_PARAM9_KEY
- OSD6_PARAM9_MAX
- OSD6_PARAM9_MIN
- OSD6_PARAM9_TYPE
- OSD6_PARAM9_X
- OSD6_PARAM9_Y
- OSD6_SAVE_X
- OSD6_SAVE_Y
- OSD_ARM_SCR
- OSD_BTN_DELAY
- OSD_CELL_COUNT
- OSD_CHAN
- OSD_DSARM_SCR
- OSD_FONT
- OSD_FS_SCR
- OSD_H_OFFSET
- OSD_MSG_TIME
- OSD_OPTIONS
- OSD_SB_H_OFS
- OSD_SB_V_EXT
- OSD_SW_METHOD
- OSD_TYPE
- OSD_TYPE2
- OSD_UNITS
- OSD_V_OFFSET
- OSD_W_ACRVOLT
- OSD_W_AVGCELLV
- OSD_W_BATVOLT
- OSD_W_LQ
- OSD_W_NSAT
- OSD_W_RESTVOLT
- OSD_W_RSSI
- OSD_W_SNR
- OSD_W_TERR
