params:
  PLND_ENABLED: 0
  RNGFND1_TYPE: 0
  RNGFND2_TYPE: 0
  RNGFND3_TYPE: 0
  RNGFND4_TYPE: 0
  RNGFND5_TYPE: 0
  RNGFND6_TYPE: 0
  RNGFND7_TYPE: 0
  RNGFND8_TYPE: 0
  RNGFND9_TYPE: 0
  RNGFNDA_TYPE: 0
