params:
  SERVO10_FUNCTION: 70
  SERVO10_MAX: 1900
  SERVO10_MIN: 1100
  SERVO10_REVERSED: 0
  SERVO10_TRIM: 1100
  SERVO11_FUNCTION: 0
  SERVO11_MAX: 1900
  SERVO11_MIN: 1100
  SERVO11_REVERSED: 0
  SERVO11_TRIM: 1500
  SERVO12_FUNCTION: 0
  SERVO12_MAX: 1900
  SERVO12_MIN: 1100
  SERVO12_REVERSED: 0
  SERVO12_TRIM: 1500
  SERVO13_FUNCTION: 0
  SERVO13_MAX: 1900
  SERVO13_MIN: 1100
  SERVO13_REVERSED: 0
  SERVO13_TRIM: 1500
  SERVO14_FUNCTION: 0
  SERVO14_MAX: 1900
  SERVO14_MIN: 1100
  SERVO14_REVERSED: 0
  SERVO14_TRIM: 1500
  SERVO15_FUNCTION: 0
  SERVO15_MAX: 1900
  SERVO15_MIN: 1100
  SERVO15_REVERSED: 0
  SERVO15_TRIM: 1500
  SERVO16_FUNCTION: 0
  SERVO16_MAX: 1900
  SERVO16_MIN: 1100
  SERVO16_REVERSED: 0
  SERVO16_TRIM: 1500
  SERVO1_FUNCTION: 0
  SERVO1_MAX: 2000
  SERVO1_MIN: 1000
  SERVO1_REVERSED: 1
  SERVO1_TRIM: 1000
  SERVO2_FUNCTION: 0
  SERVO2_MAX: 2000
  SERVO2_MIN: 1000
  SERVO2_REVERSED: 0
  SERVO2_TRIM: 1000
  SERVO3_FUNCTION: 4
  SERVO3_MAX: 1785
  SERVO3_MIN: 1185
  SERVO3_REVERSED: 1
  SERVO3_TRIM: 1437
  SERVO4_FUNCTION: 80
  SERVO4_MAX: 1770
  SERVO4_MIN: 1170
  SERVO4_REVERSED: 1
  SERVO4_TRIM: 1444
  SERVO5_FUNCTION: 79
  SERVO5_MAX: 1800
  SERVO5_MIN: 1200
  SERVO5_REVERSED: 0
  SERVO5_TRIM: 1526
  SERVO6_FUNCTION: 4
  SERVO6_MAX: 1820
  SERVO6_MIN: 1220
  SERVO6_REVERSED: 1
  SERVO6_TRIM: 1472
  SERVO7_FUNCTION: 0
  SERVO7_MAX: 1900
  SERVO7_MIN: 1100
  SERVO7_REVERSED: 0
  SERVO7_TRIM: 1500
  SERVO8_FUNCTION: 0
  SERVO8_MAX: 1900
  SERVO8_MIN: 1100
  SERVO8_REVERSED: 0
  SERVO8_TRIM: 1500
  SERVO9_FUNCTION: 0
  SERVO9_MAX: 1900
  SERVO9_MIN: 1100
  SERVO9_REVERSED: 0
  SERVO9_TRIM: 1488
  SERVO_32_ENABLE: 0
  SERVO_AUTO_TRIM: 1
  SERVO_BLH_3DMASK: 0
  SERVO_BLH_AUTO: 1
  SERVO_BLH_BDMASK: 0
  SERVO_BLH_DEBUG: 0
  SERVO_BLH_MASK: 3
  SERVO_BLH_OTYPE: 6
  SERVO_BLH_POLES: 14
  SERVO_BLH_PORT: 0
  SERVO_BLH_RVMASK: 0
  SERVO_BLH_TEST: 0
  SERVO_BLH_TMOUT: 0
  SERVO_BLH_TRATE: 10
  SERVO_DSHOT_ESC: 3
  SERVO_DSHOT_RATE: 0
  SERVO_FTW_MASK: 0
  SERVO_FTW_POLES: 14
  SERVO_FTW_RVMASK: 0
  SERVO_GPIO_MASK: 0
  SERVO_RATE: 50
  SERVO_RC_FS_MSK: 0
  SERVO_ROB_POSMAX: 4095
  SERVO_ROB_POSMIN: 0
  SERVO_SBUS_RATE: 50
  SERVO_VOLZ_MASK: 0
  SERVO_VOLZ_RANGE: 200
