params:
  SERIAL0_BAUD: 115
  SERIAL0_PROTOCOL: 2
  SERIAL1_BAUD: 57
  SERIAL1_OPTIONS: 0
  SERIAL1_PROTOCOL: -1
  SERIAL2_BAUD: 921
  SERIAL2_OPTIONS: 0
  SERIAL2_PROTOCOL: 2
  SERIAL3_BAUD: 230
  SERIAL3_OPTIONS: 0
  SERIAL3_PROTOCOL: 5
  SERIAL4_BAUD: 4
  SERIAL4_OPTIONS: 0
  SERIAL4_PROTOCOL: 37
  SERIAL5_BAUD: 115
  SERIAL5_OPTIONS: 0
  SERIAL5_PROTOCOL: 16
  SERIAL6_BAUD: 57
  SERIAL6_OPTIONS: 0
  SERIAL6_PROTOCOL: 2
  SERIAL7_BAUD: 460
  SERIAL7_OPTIONS: 0
  SERIAL7_PROTOCOL: 2
  SERIAL8_BAUD: 115200
  SERIAL8_OPTIONS: 0
  SERIAL8_PROTOCOL: 2
  SERIAL_PASS1: 0
  SERIAL_PASS2: -1
  SERIAL_PASSTIMO: 15
