params:
  BARO1_DEVID: 423425
  BARO1_GND_PRESS: 98608.8828125
  BARO1_WCF_ENABLE: 0
  BARO2_DEVID: 0
  BARO2_GND_PRESS: 0
  BARO2_WCF_ENABLE: 0
  BARO3_DEVID: 0
  BARO3_GND_PRESS: 0
  BARO3_WCF_ENABLE: 0
  BARO_ALTERR_MAX: 2000
  BARO_ALT_OFFSET: 0
  BARO_EXT_BUS: -1
  BARO_FIELD_ELV: 0
  BARO_FLTR_RNG: 0
  BARO_GND_TEMP: 0
  BARO_OPTIONS: 0
  BARO_PRIMARY: 0
  BARO_PROBE_EXT: 0
