params:
  BRD_ALT_CONFIG: 1
  BRD_BOOT_DELAY: 0
  BRD_OPTIONS: 1
  BRD_RTC_TYPES: 1
  BRD_RTC_TZ_MIN: 0
  BRD_SAFETYOPTION: 3
  BRD_SAFETY_DEFLT: 0
  BRD_SAFETY_MASK: 0
  BRD_SD_FENCE: 0
  BRD_SD_MISSION: 0
  BRD_SD_SLOWDOWN: 0
  BRD_SER1_RTSCTS: 2
  BRD_SERIAL_NUM: 0
