params:
  CAN_D1_PROTOCOL: 1
  CAN_D1_PROTOCOL2: 0
  CAN_D1_UC_ESC_BM: 0
  CAN_D1_UC_ESC_OF: 0
  CAN_D1_UC_ESC_RV: 0
  CAN_D1_UC_NODE: 10
  CAN_D1_UC_NTF_RT: 20
  CAN_D1_UC_OPTION: 0
  CAN_D1_UC_POOL: 16384
  CAN_D1_UC_RLY_RT: 0
  CAN_D1_UC_SER_EN: 0
  CAN_D1_UC_SRV_BM: 0
  CAN_D1_UC_SRV_RT: 50
  CAN_LOGLEVEL: 0
  CAN_P1_BITRATE: 1000000
  CAN_P1_DRIVER: 1
  CAN_P1_FDBITRATE: 4
  CAN_P1_OPTIONS: 0
  CAN_SLCAN_CPORT: 0
  CAN_SLCAN_SDELAY: 1
  CAN_SLCAN_SERNUM: -1
  CAN_SLCAN_TIMOUT: 0
