name: can_bus
description: ArduPilot can_bus parameters
version: schema
schema_params:
- CAN_D1_PC_ECU_ID
- CAN_D1_PC_ECU_RT
- CAN_D1_PC_ESC_BM
- CAN_D1_PC_ESC_RT
- CAN_D1_PC_SRV_BM
- CAN_D1_PC_SRV_RT
- CAN_D1_PROTOCOL
- CAN_D1_PROTOCOL2
- CAN_D1_UC_ESC_BM
- CAN_D1_UC_ESC_OF
- CAN_D1_UC_ESC_RV
- CAN_D1_UC_NODE
- CAN_D1_UC_NTF_RT
- CAN_D1_UC_OPTION
- CAN_D1_UC_POOL
- CAN_D1_UC_RLY_RT
- CAN_D1_UC_S1_BD
- CAN_D1_UC_S1_IDX
- CAN_D1_UC_S1_NOD
- CAN_D1_UC_S1_PRO
- CAN_D1_UC_S2_BD
- CAN_D1_UC_S2_IDX
- CAN_D1_UC_S2_NOD
- CAN_D1_UC_S2_PRO
- CAN_D1_UC_S3_BD
- CAN_D1_UC_S3_IDX
- CAN_D1_UC_S3_NOD
- CAN_D1_UC_S3_PRO
- CAN_D1_UC_SER_EN
- CAN_D1_UC_SRV_BM
- CAN_D1_UC_SRV_RT
- CAN_D2_PC_ECU_ID
- CAN_D2_PC_ECU_RT
- CAN_D2_PC_ESC_BM
- CAN_D2_PC_ESC_RT
- CAN_D2_PC_SRV_BM
- CAN_D2_PC_SRV_RT
- CAN_D2_PROTOCOL
- CAN_D2_PROTOCOL2
- CAN_D2_UC_ESC_BM
- CAN_D2_UC_ESC_OF
- CAN_D2_UC_ESC_RV
- CAN_D2_UC_NODE
- CAN_D2_UC_NTF_RT
- CAN_D2_UC_OPTION
- CAN_D2_UC_POOL
- CAN_D2_UC_RLY_RT
- CAN_D2_UC_S1_BD
- CAN_D2_UC_S1_IDX
- CAN_D2_UC_S1_NOD
- CAN_D2_UC_S1_PRO
- CAN_D2_UC_S2_BD
- CAN_D2_UC_S2_IDX
- CAN_D2_UC_S2_NOD
- CAN_D2_UC_S2_PRO
- CAN_D2_UC_S3_BD
- CAN_D2_UC_S3_IDX
- CAN_D2_UC_S3_NOD
- CAN_D2_UC_S3_PRO
- CAN_D2_UC_SER_EN
- CAN_D2_UC_SRV_BM
- CAN_D2_UC_SRV_RT
- CAN_D3_PC_ECU_ID
- CAN_D3_PC_ECU_RT
- CAN_D3_PC_ESC_BM
- CAN_D3_PC_ESC_RT
- CAN_D3_PC_SRV_BM
- CAN_D3_PC_SRV_RT
- CAN_D3_PROTOCOL
- CAN_D3_PROTOCOL2
- CAN_D3_UC_ESC_BM
- CAN_D3_UC_ESC_OF
- CAN_D3_UC_ESC_RV
- CAN_D3_UC_NODE
- CAN_D3_UC_NTF_RT
- CAN_D3_UC_OPTION
- CAN_D3_UC_POOL
- CAN_D3_UC_RLY_RT
- CAN_D3_UC_S1_BD
- CAN_D3_UC_S1_IDX
- CAN_D3_UC_S1_NOD
- CAN_D3_UC_S1_PRO
- CAN_D3_UC_S2_BD
- CAN_D3_UC_S2_IDX
- CAN_D3_UC_S2_NOD
- CAN_D3_UC_S2_PRO
- CAN_D3_UC_S3_BD
- CAN_D3_UC_S3_IDX
- CAN_D3_UC_S3_NOD
- CAN_D3_UC_S3_PRO
- CAN_D3_UC_SER_EN
- CAN_D3_UC_SRV_BM
- CAN_D3_UC_SRV_RT
- CAN_LOGLEVEL
- CAN_P1_BITRATE
- CAN_P1_DRIVER
- CAN_P1_FDBITRATE
- CAN_P1_OPTIONS
- CAN_P2_BITRATE
- CAN_P2_DRIVER
- CAN_P2_FDBITRATE
- CAN_P2_OPTIONS
- CAN_P3_BITRATE
- CAN_P3_DRIVER
- CAN_P3_FDBITRATE
- CAN_P3_OPTIONS
- CAN_SLCAN_CPORT
- CAN_SLCAN_SDELAY
- CAN_SLCAN_SERNUM
- CAN_SLCAN_TIMOUT
