params:
  BATT2_MONITOR: 0
  BATT3_MONITOR: 0
  BATT4_MONITOR: 0
  BATT5_MONITOR: 0
  BATT6_MONITOR: 0
  BATT7_MONITOR: 0
  BATT8_MONITOR: 0
  BATT9_MONITOR: 0
  BATT_AMP_OFFSET: 0
  BATT_AMP_PERVLT: 66.69999694824219
  BATT_ARM_MAH: 0
  BATT_ARM_VOLT: 22.200000762939453
  BATT_CAPACITY: 6000
  BATT_CRT_MAH: 150
  BATT_CRT_VOLT: 20.399999618530273
  BATT_CURR_PIN: 11
  BATT_FS_CRT_ACT: 2
  BATT_FS_LOW_ACT: 1
  BATT_FS_VOLTSRC: 0
  BATT_LOW_MAH: 450
  BATT_LOW_TIMER: 8
  BATT_LOW_VOLT: 21.600000381469727
  BATT_MONITOR: 4
  BATT_OPTIONS: 0
  BATT_SERIAL_NUM: -1
  BATT_VLT_OFFSET: 0
  BATT_VOLT_MULT: 11.100000381469727
  BATT_VOLT_PIN: 10
  BATT_WATT_MAX: 0
