name: airspeed
description: ArduPilot airspeed parameters
version: schema
schema_params:
- ARSPD2_AUTOCAL
- ARSPD2_BUS
- ARSPD2_DEVID
- ARSPD2_OFFSET
- ARSPD2_PIN
- ARSPD2_PSI_RANGE
- ARSPD2_RATIO
- ARSPD2_SKIP_CAL
- ARSPD2_TUBE_ORDR
- ARSPD2_TYPE
- ARSPD2_USE
- ARSPD3_AUTOCAL
- ARSPD3_BUS
- ARSPD3_DEVID
- ARSPD3_OFFSET
- ARSPD3_PIN
- ARSPD3_PSI_RANGE
- ARSPD3_RATIO
- ARSPD3_SKIP_CAL
- ARSPD3_TUBE_ORDR
- ARSPD3_TYPE
- ARSPD3_USE
- ARSPD4_AUTOCAL
- ARSPD4_BUS
- ARSPD4_DEVID
- ARSPD4_OFFSET
- ARSPD4_PIN
- ARSPD4_PSI_RANGE
- ARSPD4_RATIO
- ARSPD4_SKIP_CAL
- ARSPD4_TUBE_ORDR
- ARSPD4_TYPE
- ARSPD4_USE
- ARSPD5_AUTOCAL
- ARSPD5_BUS
- ARSPD5_DEVID
- ARSPD5_OFFSET
- ARSPD5_PIN
- ARSPD5_PSI_RANGE
- ARSPD5_RATIO
- ARSPD5_SKIP_CAL
- ARSPD5_TUBE_ORDR
- ARSPD5_TYPE
- ARSPD5_USE
- ARSPD6_AUTOCAL
- ARSPD6_BUS
- ARSPD6_DEVID
- ARSPD6_OFFSET
- ARSPD6_PIN
- ARSPD6_PSI_RANGE
- ARSPD6_RATIO
- ARSPD6_SKIP_CAL
- ARSPD6_TUBE_ORDR
- ARSPD6_TYPE
- ARSPD6_USE
- ARSPD_AUTOCAL
- ARSPD_BUS
- ARSPD_DEVID
- ARSPD_ENABLE
- ARSPD_OFFSET
- ARSPD_OFF_PCNT
- ARSPD_OPTIONS
- ARSPD_PIN
- ARSPD_PRIMARY
- ARSPD_PSI_RANGE
- ARSPD_RATIO
- ARSPD_SKIP_CAL
- ARSPD_TUBE_ORDER
- ARSPD_TUBE_ORDR
- ARSPD_TYPE
- ARSPD_USE
- ARSPD_WIND_GATE
- ARSPD_WIND_MAX
- ARSPD_WIND_WARN
