name: compass
description: ArduPilot compass parameters
version: schema
schema_params:
- COMPASS_AUTODEC
- COMPASS_AUTO_ROT
- COMPASS_CAL_FIT
- COMPASS_CUS_PIT
- COMPASS_CUS_ROLL
- COMPASS_CUS_YAW
- COMPASS_DEC
- COMPASS_DEV_ID
- COMPASS_DEV_ID2
- COMPASS_DEV_ID3
- COMPASS_DEV_ID4
- COMPASS_DEV_ID5
- COMPASS_DEV_ID6
- COMPASS_DEV_ID7
- COMPASS_DEV_ID8
- COMPASS_DIA2_X
- COMPASS_DIA2_Y
- COMPASS_DIA2_Z
- COMPASS_DIA3_X
- COMPASS_DIA3_Y
- COMPASS_DIA3_Z
- COMPASS_DIA_X
- COMPASS_DIA_Y
- COMPASS_DIA_Z
- COMPASS_DISBLMSK
- COMPASS_ENABLE
- COMPASS_EXTERN2
- COMPASS_EXTERN3
- COMPASS_EXTERNAL
- COMPASS_FLTR_RNG
- COMPASS_LEARN
- COMPASS_MOT2_X
- COMPASS_MOT2_Y
- COMPASS_MOT2_Z
- COMPASS_MOT3_X
- COMPASS_MOT3_Y
- COMPASS_MOT3_Z
- COMPASS_MOTCT
- COMPASS_MOT_X
- COMPASS_MOT_Y
- COMPASS_MOT_Z
- COMPASS_ODI2_X
- COMPASS_ODI2_Y
- COMPASS_ODI2_Z
- COMPASS_ODI3_X
- COMPASS_ODI3_Y
- COMPASS_ODI3_Z
- COMPASS_ODI_X
- COMPASS_ODI_Y
- COMPASS_ODI_Z
- COMPASS_OFFS_MAX
- COMPASS_OFS2_X
- COMPASS_OFS2_Y
- COMPASS_OFS2_Z
- COMPASS_OFS3_X
- COMPASS_OFS3_Y
- COMPASS_OFS3_Z
- COMPASS_OFS_X
- COMPASS_OFS_Y
- COMPASS_OFS_Z
- COMPASS_OPTIONS
- COMPASS_ORIENT
- COMPASS_ORIENT2
- COMPASS_ORIENT3
- COMPASS_PMOT1_X
- COMPASS_PMOT1_Y
- COMPASS_PMOT1_Z
- COMPASS_PMOT2_X
- COMPASS_PMOT2_Y
- COMPASS_PMOT2_Z
- COMPASS_PMOT3_X
- COMPASS_PMOT3_Y
- COMPASS_PMOT3_Z
- COMPASS_PMOT4_X
- COMPASS_PMOT4_Y
- COMPASS_PMOT4_Z
- COMPASS_PMOT_EN
- COMPASS_PMOT_EXP
- COMPASS_PRIO1_ID
- COMPASS_PRIO2_ID
- COMPASS_PRIO3_ID
- COMPASS_SCALE
- COMPASS_SCALE2
- COMPASS_SCALE3
- COMPASS_USE
- COMPASS_USE2
- COMPASS_USE3
