name: imu
description: ArduPilot imu parameters
version: schema
schema_params:
- FFT_ATT_REF
- FFT_BW_HOVER
- FFT_ENABLE
- FFT_FREQ_HOVER
- FFT_HMNC_FIT
- FFT_HMNC_PEAK
- FFT_MAXHZ
- FFT_MINHZ
- FFT_NUM_FRAMES
- FFT_OPTIONS
- FFT_SAMPLE_MODE
- FFT_SNR_REF
- FFT_THR_REF
- FFT_WINDOW_OLAP
- FFT_WINDOW_SIZE
- FILT1_NOTCH_ATT
- FILT1_NOTCH_FREQ
- FILT1_NOTCH_Q
- FILT1_TYPE
- FILT2_NOTCH_ATT
- FILT2_NOTCH_FREQ
- FILT2_NOTCH_Q
- FILT2_TYPE
- FILT3_NOTCH_ATT
- FILT3_NOTCH_FREQ
- FILT3_NOTCH_Q
- FILT3_TYPE
- FILT4_NOTCH_ATT
- FILT4_NOTCH_FREQ
- FILT4_NOTCH_Q
- FILT4_TYPE
- FILT5_NOTCH_ATT
- FILT5_NOTCH_FREQ
- FILT5_NOTCH_Q
- FILT5_TYPE
- FILT6_NOTCH_ATT
- FILT6_NOTCH_FREQ
- FILT6_NOTCH_Q
- FILT6_TYPE
- FILT7_NOTCH_ATT
- FILT7_NOTCH_FREQ
- FILT7_NOTCH_Q
- FILT7_TYPE
- FILT8_NOTCH_ATT
- FILT8_NOTCH_FREQ
- FILT8_NOTCH_Q
- FILT8_TYPE
- INS4_ACCOFFS_X
- INS4_ACCOFFS_Y
- INS4_ACCOFFS_Z
- INS4_ACCSCAL_X
- INS4_ACCSCAL_Y
- INS4_ACCSCAL_Z
- INS4_ACC_CALTEMP
- INS4_ACC_ID
- INS4_GYROFFS_X
- INS4_GYROFFS_Y
- INS4_GYROFFS_Z
- INS4_GYR_CALTEMP
- INS4_GYR_ID
- INS4_POS_X
- INS4_POS_Y
- INS4_POS_Z
- INS4_TCAL_ACC1_X
- INS4_TCAL_ACC1_Y
- INS4_TCAL_ACC1_Z
- INS4_TCAL_ACC2_X
- INS4_TCAL_ACC2_Y
- INS4_TCAL_ACC2_Z
- INS4_TCAL_ACC3_X
- INS4_TCAL_ACC3_Y
- INS4_TCAL_ACC3_Z
- INS4_TCAL_ENABLE
- INS4_TCAL_GYR1_X
- INS4_TCAL_GYR1_Y
- INS4_TCAL_GYR1_Z
- INS4_TCAL_GYR2_X
- INS4_TCAL_GYR2_Y
- INS4_TCAL_GYR2_Z
- INS4_TCAL_GYR3_X
- INS4_TCAL_GYR3_Y
- INS4_TCAL_GYR3_Z
- INS4_TCAL_TMAX
- INS4_TCAL_TMIN
- INS4_USE
- INS5_ACCOFFS_X
- INS5_ACCOFFS_Y
- INS5_ACCOFFS_Z
- INS5_ACCSCAL_X
- INS5_ACCSCAL_Y
- INS5_ACCSCAL_Z
- INS5_ACC_CALTEMP
- INS5_ACC_ID
- INS5_GYROFFS_X
- INS5_GYROFFS_Y
- INS5_GYROFFS_Z
- INS5_GYR_CALTEMP
- INS5_GYR_ID
- INS5_POS_X
- INS5_POS_Y
- INS5_POS_Z
- INS5_TCAL_ACC1_X
- INS5_TCAL_ACC1_Y
- INS5_TCAL_ACC1_Z
- INS5_TCAL_ACC2_X
- INS5_TCAL_ACC2_Y
- INS5_TCAL_ACC2_Z
- INS5_TCAL_ACC3_X
- INS5_TCAL_ACC3_Y
- INS5_TCAL_ACC3_Z
- INS5_TCAL_ENABLE
- INS5_TCAL_GYR1_X
- INS5_TCAL_GYR1_Y
- INS5_TCAL_GYR1_Z
- INS5_TCAL_GYR2_X
- INS5_TCAL_GYR2_Y
- INS5_TCAL_GYR2_Z
- INS5_TCAL_GYR3_X
- INS5_TCAL_GYR3_Y
- INS5_TCAL_GYR3_Z
- INS5_TCAL_TMAX
- INS5_TCAL_TMIN
- INS5_USE
- INS_ACC1_CALTEMP
- INS_ACC2OFFS_X
- INS_ACC2OFFS_Y
- INS_ACC2OFFS_Z
- INS_ACC2SCAL_X
- INS_ACC2SCAL_Y
- INS_ACC2SCAL_Z
- INS_ACC2_CALTEMP
- INS_ACC2_ID
- INS_ACC3OFFS_X
- INS_ACC3OFFS_Y
- INS_ACC3OFFS_Z
- INS_ACC3SCAL_X
- INS_ACC3SCAL_Y
- INS_ACC3SCAL_Z
- INS_ACC3_CALTEMP
- INS_ACC3_ID
- INS_ACCEL_FILTER
- INS_ACCOFFS_X
- INS_ACCOFFS_Y
- INS_ACCOFFS_Z
- INS_ACCSCAL_X
- INS_ACCSCAL_Y
- INS_ACCSCAL_Z
- INS_ACC_BODYFIX
- INS_ACC_ID
- INS_ENABLE_MASK
- INS_FAST_SAMPLE
- INS_GYR1_CALTEMP
- INS_GYR2OFFS_X
- INS_GYR2OFFS_Y
- INS_GYR2OFFS_Z
- INS_GYR2_CALTEMP
- INS_GYR2_ID
- INS_GYR3OFFS_X
- INS_GYR3OFFS_Y
- INS_GYR3OFFS_Z
- INS_GYR3_CALTEMP
- INS_GYR3_ID
- INS_GYROFFS_X
- INS_GYROFFS_Y
- INS_GYROFFS_Z
- INS_GYRO_FILTER
- INS_GYRO_RATE
- INS_GYR_CAL
- INS_GYR_ID
- INS_HNTC2_ATT
- INS_HNTC2_BW
- INS_HNTC2_ENABLE
- INS_HNTC2_FM_RAT
- INS_HNTC2_FREQ
- INS_HNTC2_HMNCS
- INS_HNTC2_MODE
- INS_HNTC2_OPTS
- INS_HNTC2_REF
- INS_HNTC3_ATT
- INS_HNTC3_BW
- INS_HNTC3_ENABLE
- INS_HNTC3_FM_RAT
- INS_HNTC3_FREQ
- INS_HNTC3_HMNCS
- INS_HNTC3_MODE
- INS_HNTC3_OPTS
- INS_HNTC3_REF
- INS_HNTC4_ATT
- INS_HNTC4_BW
- INS_HNTC4_ENABLE
- INS_HNTC4_FM_RAT
- INS_HNTC4_FREQ
- INS_HNTC4_HMNCS
- INS_HNTC4_MODE
- INS_HNTC4_OPTS
- INS_HNTC4_REF
- INS_HNTCH_ATT
- INS_HNTCH_BW
- INS_HNTCH_ENABLE
- INS_HNTCH_FM_RAT
- INS_HNTCH_FREQ
- INS_HNTCH_HMNCS
- INS_HNTCH_MODE
- INS_HNTCH_OPTS
- INS_HNTCH_REF
- INS_LOG_BAT_CNT
- INS_LOG_BAT_LGCT
- INS_LOG_BAT_LGIN
- INS_LOG_BAT_MASK
- INS_LOG_BAT_OPT
- INS_POS1_X
- INS_POS1_Y
- INS_POS1_Z
- INS_POS2_X
- INS_POS2_Y
- INS_POS2_Z
- INS_POS3_X
- INS_POS3_Y
- INS_POS3_Z
- INS_RAW_LOG_OPT
- INS_STILL_THRESH
- INS_TCAL1_ACC1_X
- INS_TCAL1_ACC1_Y
- INS_TCAL1_ACC1_Z
- INS_TCAL1_ACC2_X
- INS_TCAL1_ACC2_Y
- INS_TCAL1_ACC2_Z
- INS_TCAL1_ACC3_X
- INS_TCAL1_ACC3_Y
- INS_TCAL1_ACC3_Z
- INS_TCAL1_ENABLE
- INS_TCAL1_GYR1_X
- INS_TCAL1_GYR1_Y
- INS_TCAL1_GYR1_Z
- INS_TCAL1_GYR2_X
- INS_TCAL1_GYR2_Y
- INS_TCAL1_GYR2_Z
- INS_TCAL1_GYR3_X
- INS_TCAL1_GYR3_Y
- INS_TCAL1_GYR3_Z
- INS_TCAL1_TMAX
- INS_TCAL1_TMIN
- INS_TCAL2_ACC1_X
- INS_TCAL2_ACC1_Y
- INS_TCAL2_ACC1_Z
- INS_TCAL2_ACC2_X
- INS_TCAL2_ACC2_Y
- INS_TCAL2_ACC2_Z
- INS_TCAL2_ACC3_X
- INS_TCAL2_ACC3_Y
- INS_TCAL2_ACC3_Z
- INS_TCAL2_ENABLE
- INS_TCAL2_GYR1_X
- INS_TCAL2_GYR1_Y
- INS_TCAL2_GYR1_Z
- INS_TCAL2_GYR2_X
- INS_TCAL2_GYR2_Y
- INS_TCAL2_GYR2_Z
- INS_TCAL2_GYR3_X
- INS_TCAL2_GYR3_Y
- INS_TCAL2_GYR3_Z
- INS_TCAL2_TMAX
- INS_TCAL2_TMIN
- INS_TCAL3_ACC1_X
- INS_TCAL3_ACC1_Y
- INS_TCAL3_ACC1_Z
- INS_TCAL3_ACC2_X
- INS_TCAL3_ACC2_Y
- INS_TCAL3_ACC2_Z
- INS_TCAL3_ACC3_X
- INS_TCAL3_ACC3_Y
- INS_TCAL3_ACC3_Z
- INS_TCAL3_ENABLE
- INS_TCAL3_GYR1_X
- INS_TCAL3_GYR1_Y
- INS_TCAL3_GYR1_Z
- INS_TCAL3_GYR2_X
- INS_TCAL3_GYR2_Y
- INS_TCAL3_GYR2_Z
- INS_TCAL3_GYR3_X
- INS_TCAL3_GYR3_Y
- INS_TCAL3_GYR3_Z
- INS_TCAL3_TMAX
- INS_TCAL3_TMIN
- INS_TCAL_OPTIONS
- INS_TRIM_OPTION
- INS_USE
- INS_USE2
- INS_USE3
