params:
  SCR_DEBUG_OPTS: 0
  SCR_DIR_DISABLE: 0
  SCR_ENABLE: 1
  SCR_HEAP_SIZE: 204800
  SCR_LD_CHECKSUM: -1
  SCR_RUN_CHECKSUM: -1
  SCR_SDEV1_PROTO: -1
  SCR_SDEV2_PROTO: -1
  SCR_SDEV3_PROTO: -1
  SCR_SDEV_EN: 1
  SCR_THD_PRIORITY: 0
  SCR_USER1: 0
  SCR_USER2: 0
  SCR_USER3: 0
  SCR_USER4: 0
  SCR_USER5: 0
  SCR_USER6: 0
  SCR_VM_I_COUNT: 10000
