name: barometer
description: ArduPilot barometer parameters
version: schema
schema_params:
- BARO1_DEVID
- BARO1_GND_PRESS
- BARO1_THST_SCALE
- BARO1_WCF_BCK
- BARO1_WCF_DN
- BARO1_WCF_ENABLE
- BARO1_WCF_FWD
- BARO1_WCF_LFT
- BARO1_WCF_RGT
- BARO1_WCF_UP
- BARO2_DEVID
- BARO2_GND_PRESS
- BARO2_WCF_BCK
- BARO2_WCF_DN
- BARO2_WCF_ENABLE
- BARO2_WCF_FWD
- BARO2_WCF_LFT
- BARO2_WCF_RGT
- BARO2_WCF_UP
- BARO3_DEVID
- BARO3_GND_PRESS
- BARO3_WCF_BCK
- BARO3_WCF_DN
- BARO3_WCF_ENABLE
- BARO3_WCF_FWD
- BARO3_WCF_LFT
- BARO3_WCF_RGT
- BARO3_WCF_UP
- BARO_ALTERR_MAX
- BARO_ALT_OFFSET
- BARO_EXT_BUS
- BARO_FIELD_ELV
- BARO_FLTR_RNG
- BARO_GND_TEMP
- BARO_OPTIONS
- BARO_PRIMARY
- BARO_PROBE_EXT
