params:
  MNT1_DEFLT_MODE: 3
  MNT1_DEVID: 0
  MNT1_LEAD_PTCH: 0
  MNT1_LEAD_RLL: 0
  MNT1_NEUTRAL_X: 0
  MNT1_NEUTRAL_Y: 0
  MNT1_NEUTRAL_Z: 0
  MNT1_OPTIONS: 0
  MNT1_PITCH_MAX: 20
  MNT1_PITCH_MIN: -90
  MNT1_RC_RATE: 0
  MNT1_RETRACT_X: 0
  MNT1_RETRACT_Y: 0
  MNT1_RETRACT_Z: 0
  MNT1_ROLL_MAX: 30
  MNT1_ROLL_MIN: -30
  MNT1_SYSID_DFLT: 0
  MNT1_TYPE: 1
  MNT1_YAW_MAX: 180
  MNT1_YAW_MIN: -180
  MNT2_TYPE: 0
