name: serial
description: ArduPilot serial parameters
version: schema
schema_params:
- SERIAL0_BAUD
- SERIAL0_PROTOCOL
- SERIAL1_BAUD
- SERIAL1_OPTIONS
- SERIAL1_PROTOCOL
- SERIAL2_BAUD
- SERIAL2_OPTIONS
- SERIAL2_PROTOCOL
- SERIAL3_BAUD
- SERIAL3_OPTIONS
- SERIAL3_PROTOCOL
- SERIAL4_BAUD
- SERIAL4_OPTIONS
- SERIAL4_PROTOCOL
- SERIAL5_BAUD
- SERIAL5_OPTIONS
- SERIAL5_PROTOCOL
- SERIAL6_BAUD
- SERIAL6_OPTIONS
- SERIAL6_PROTOCOL
- SERIAL7_BAUD
- SERIAL7_OPTIONS
- SERIAL7_PROTOCOL
- SERIAL8_BAUD
- SERIAL8_OPTIONS
- SERIAL8_PROTOCOL
- SERIAL9_BAUD
- SERIAL9_OPTIONS
- SERIAL9_PROTOCOL
- SERIAL_PASS1
- SERIAL_PASS2
- SERIAL_PASSTIMO
