params:
  ACRO_LOCKING: 0
  ACRO_PITCH_RATE: 120
  ACRO_ROLL_RATE: 120
  ACRO_YAW_RATE: 90
  AIRSPEED_CRUISE: 12
  AIRSPEED_MAX: 22
  AIRSPEED_MIN: 9
  AIRSPEED_STALL: 0
  ALT_OFFSET: 0
  AUTOTUNE_AXES: 7
  AUTOTUNE_LEVEL: 6
  AUTOTUNE_OPTIONS: 0
  CRASH_ACC_THRESH: 0
  CRASH_DETECT: 0
  CRUISE_ALT_FLOOR: 0
  DSPOILER_AILMTCH: 100
  DSPOILER_CROW_W1: 0
  DSPOILER_CROW_W2: 0
  DSPOILER_OPTS: 3
  DSPOILR_RUD_RATE: 100
  FBWB_CLIMB_RATE: 2
  FBWB_ELEV_REV: 0
  FLAP_1_PERCNT: 0
  FLAP_1_SPEED: 0
  FLAP_2_PERCNT: 0
  FLAP_2_SPEED: 0
  FLAP_SLEWRATE: 75
  FLIGHT_OPTIONS: 0
  FLTMODE1: 0
  FLTMODE2: 5
  FLTMODE3: 13
  FLTMODE4: 5
  FLTMODE5: 8
  FLTMODE6: 12
  FLTMODE_CH: 6
  FORMAT_VERSION: 13
  FS_EKF_THRESH: 0.800000011920929
  FS_GCS_ENABL: 0
  FS_LONG_ACTN: 0
  FS_LONG_TIMEOUT: 5
  FS_SHORT_ACTN: 3
  FWD_BAT_IDX: 0
  FWD_BAT_VOLT_MAX: 25.200000762939453
  FWD_BAT_VOLT_MIN: 20.399999618530273
  GCS_PID_MASK: 0
  GROUND_STEER_ALT: 0
  GROUND_STEER_DPS: 90
  GUIDED_D: 0
  GUIDED_D_FF: 0
  GUIDED_FF: 0
  GUIDED_FLTD: 5
  GUIDED_FLTE: 5
  GUIDED_FLTT: 5
  GUIDED_I: 0
  GUIDED_IMAX: 10
  GUIDED_NEF: 0
  GUIDED_NTF: 0
  GUIDED_P: 5000
  GUIDED_PDMX: 0
  GUIDED_SMAX: 0
  HOME_RESET_ALT: 0
  INITIAL_MODE: 0
  KFF_RDDRMIX: 0.5
  KFF_THR2PTCH: 0
  LEVEL_ROLL_LIMIT: 5
  LOG_BITMASK: 145118
  MANUAL_RCMASK: 0
  MAN_EXPO_PITCH: 80
  MAN_EXPO_ROLL: 80
  MAN_EXPO_RUDDER: 80
  MIN_GROUNDSPEED: 0
  MIXING_GAIN: 1
  MIXING_OFFSET: 0
  NAVL1_DAMPING: 0.75
  NAVL1_LIM_BANK: 0
  NAVL1_PERIOD: 17
  NAVL1_XTRACK_I: 0.019999999552965164
  ONESHOT_MASK: 0
  PTCH2SRV_RLL: 1
  PTCH2SRV_RMAX_DN: 0
  PTCH2SRV_RMAX_UP: 0
  PTCH2SRV_TCONST: 0.5
  PTCH_LIM_MAX_DEG: 20
  PTCH_LIM_MIN_DEG: -25
  PTCH_RATE_D: 0.008706100285053253
  PTCH_RATE_D_FF: 0
  PTCH_RATE_FF: 0.19041459262371063
  PTCH_RATE_FLTD: 10
  PTCH_RATE_FLTE: 0
  PTCH_RATE_FLTT: 2.122066020965576
  PTCH_RATE_I: 0.19041459262371063
  PTCH_RATE_IMAX: 0.6660000085830688
  PTCH_RATE_NEF: 0
  PTCH_RATE_NTF: 0
  PTCH_RATE_P: 0.13378840684890747
  PTCH_RATE_PDMX: 0
  PTCH_RATE_SMAX: 100
  PTCH_TRIM_DEG: 0
  RLL2SRV_RMAX: 0
  RLL2SRV_TCONST: 0.5
  RLL_RATE_D: 0.0012259000213816762
  RLL_RATE_D_FF: 0
  RLL_RATE_FF: 0.16775520145893097
  RLL_RATE_FLTD: 10
  RLL_RATE_FLTE: 0
  RLL_RATE_FLTT: 3.1830990314483643
  RLL_RATE_I: 0.04331519827246666
  RLL_RATE_IMAX: 0.6660000085830688
  RLL_RATE_NEF: 0
  RLL_RATE_NTF: 0
  RLL_RATE_P: 0.04331519827246666
  RLL_RATE_PDMX: 0
  RLL_RATE_SMAX: 100
  RNGFND_LANDING: 0
  RNGFND_LND_ORNT: 25
  ROLL_LIMIT_DEG: 45
  RTL_ALTITUDE: 120
  RTL_AUTOLAND: 1
  RTL_CLIMB_MIN: 0
  RTL_RADIUS: 200
  RUDDER_ONLY: 0
  RUDD_DT_GAIN: 10
  SCALING_SPEED: 40
  STAB_PITCH_DOWN: 2
  STALL_PREVENTION: 1
  STEER2SRV_D: 0.004999999888241291
  STEER2SRV_DRTFCT: 10
  STEER2SRV_DRTMIN: 4500
  STEER2SRV_DRTSPD: 0
  STEER2SRV_FF: 0
  STEER2SRV_I: 0.20000000298023224
  STEER2SRV_IMAX: 1500
  STEER2SRV_MINSPD: 1
  STEER2SRV_P: 1.7999999523162842
  STEER2SRV_TCONST: 0.75
  STICK_MIXING: 1
  TECS_APPR_SMAX: 0
  TECS_CLMB_MAX: 10
  TECS_FLARE_HGT: 1
  TECS_HDEM_TCONST: 3
  TECS_HGT_OMEGA: 3
  TECS_INTEG_GAIN: 0.30000001192092896
  TECS_LAND_ARSPD: -1
  TECS_LAND_DAMP: 0.5
  TECS_LAND_IGAIN: 0
  TECS_LAND_PDAMP: 0
  TECS_LAND_PMAX: 10
  TECS_LAND_SINK: 0.25
  TECS_LAND_SPDWGT: -1
  TECS_LAND_SRC: 0
  TECS_LAND_TCONST: 2
  TECS_LAND_TDAMP: 0
  TECS_LAND_THR: -1
  TECS_OPTIONS: 0
  TECS_PITCH_MAX: 15
  TECS_PITCH_MIN: 0
  TECS_PTCH_DAMP: 0.30000001192092896
  TECS_PTCH_FF_K: 0
  TECS_PTCH_FF_V0: 12
  TECS_RLL2THR: 10
  TECS_SINK_MAX: 15
  TECS_SINK_MIN: 2
  TECS_SPDWEIGHT: 0.5
  TECS_SPD_OMEGA: 2
  TECS_SYNAIRSPEED: 0
  TECS_THR_DAMP: 0.5
  TECS_TIME_CONST: 5
  TECS_TKOFF_IGAIN: 0
  TECS_VERT_ACC: 7
  TERRAIN_FOLLOW: 0
  TERRAIN_LOOKAHD: 2000
  THROTTLE_NUDGE: 1
  THR_FAILSAFE: 1
  THR_FS_VALUE: 950
  THR_MAX: 100
  THR_MIN: 0
  THR_PASS_STAB: 0
  THR_SLEWRATE: 100
  THR_SUPP_MAN: 0
  TKOFF_ACCEL_CNT: 1
  TKOFF_FLAP_PCNT: 0
  TKOFF_OPTIONS: 0
  TKOFF_PLIM_SEC: 2
  TKOFF_ROTATE_SPD: 0
  TKOFF_TDRAG_ELEV: 0
  TKOFF_TDRAG_SPD1: 0
  TKOFF_THR_DELAY: 2
  TKOFF_THR_MAX: 80
  TKOFF_THR_MAX_T: 4
  TKOFF_THR_MIN: 0
  TKOFF_THR_MINACC: 5
  TKOFF_THR_MINSPD: 0
  TKOFF_THR_SLEW: 50
  TKOFF_TIMEOUT: 0
  TRIM_THROTTLE: 45
  USE_REV_THRUST: 2
  WP_LOITER_RAD: 100
  WP_MAX_RADIUS: 0
  WP_RADIUS: 3
  YAW2SRV_DAMP: 0
  YAW2SRV_IMAX: 1500
  YAW2SRV_INT: 0
  YAW2SRV_RLL: 1
  YAW2SRV_SLIP: 0
  YAW_RATE_D: 0
  YAW_RATE_D_FF: 0
  YAW_RATE_ENABLE: 1
  YAW_RATE_FF: 0.15000000596046448
  YAW_RATE_FLTD: 12
  YAW_RATE_FLTE: 0
  YAW_RATE_FLTT: 3
  YAW_RATE_I: 0.15000000596046448
  YAW_RATE_IMAX: 0.6660000085830688
  YAW_RATE_NEF: 0
  YAW_RATE_NTF: 0
  YAW_RATE_P: 0.03999999910593033
  YAW_RATE_PDMX: 0
  YAW_RATE_SMAX: 150
