name: soaring
description: ArduPilot soaring parameters
version: schema
schema_params:
- SOAR_ALT_CUTOFF
- SOAR_ALT_MAX
- SOAR_ALT_MIN
- SOAR_CRSE_ARSPD
- SOAR_DIST_AHEAD
- SOAR_ENABLE
- SOAR_MAX_DRIFT
- SOAR_MAX_RADIUS
- SOAR_MIN_CRSE_S
- SOAR_MIN_THML_S
- SOAR_POLAR_B
- SOAR_POLAR_CD0
- SOAR_POLAR_K
- SOAR_Q1
- SOAR_Q2
- SOAR_R
- SOAR_THML_ARSPD
- SOAR_THML_BANK
- SOAR_THML_FLAP
- SOAR_VSPEED
