name: battery
description: ArduPilot battery parameters
version: schema
schema_params:
- BATT2_AMP_OFFSET
- BATT2_AMP_PERVLT
- BATT2_ARM_MAH
- BATT2_ARM_VOLT
- BATT2_CAPACITY
- BATT2_CHANNEL
- BATT2_CRT_MAH
- BATT2_CRT_VOLT
- BATT2_CURR_MULT
- BATT2_CURR_PIN
- BATT2_ESC_INDEX
- BATT2_ESC_MASK
- BATT2_FL_FF
- BATT2_FL_FLTR
- BATT2_FL_FS
- BATT2_FL_FT
- BATT2_FL_OFF
- BATT2_FL_PIN
- BATT2_FL_VLT_MIN
- BATT2_FL_V_MULT
- BATT2_FS_CRT_ACT
- BATT2_FS_LOW_ACT
- BATT2_FS_VOLTSRC
- BATT2_I2C_ADDR
- BATT2_I2C_BUS
- BATT2_LOW_MAH
- BATT2_LOW_TIMER
- BATT2_LOW_VOLT
- BATT2_MAX_AMPS
- BATT2_MAX_VOLT
- BATT2_MONITOR
- BATT2_OPTIONS
- BATT2_SERIAL_NUM
- BATT2_SHUNT
- BATT2_SUM_MASK
- BATT2_VLT_OFFSET
- BATT2_VOLT_MULT
- BATT2_VOLT_PIN
- BATT2_WATT_MAX
- BATT3_AMP_OFFSET
- BATT3_AMP_PERVLT
- BATT3_ARM_MAH
- BATT3_ARM_VOLT
- BATT3_CAPACITY
- BATT3_CHANNEL
- BATT3_CRT_MAH
- BATT3_CRT_VOLT
- BATT3_CURR_MULT
- BATT3_CURR_PIN
- BATT3_ESC_INDEX
- BATT3_ESC_MASK
- BATT3_FL_FF
- BATT3_FL_FLTR
- BATT3_FL_FS
- BATT3_FL_FT
- BATT3_FL_OFF
- BATT3_FL_PIN
- BATT3_FL_VLT_MIN
- BATT3_FL_V_MULT
- BATT3_FS_CRT_ACT
- BATT3_FS_LOW_ACT
- BATT3_FS_VOLTSRC
- BATT3_I2C_ADDR
- BATT3_I2C_BUS
- BATT3_LOW_MAH
- BATT3_LOW_TIMER
- BATT3_LOW_VOLT
- BATT3_MAX_AMPS
- BATT3_MAX_VOLT
- BATT3_MONITOR
- BATT3_OPTIONS
- BATT3_SERIAL_NUM
- BATT3_SHUNT
- BATT3_SUM_MASK
- BATT3_VLT_OFFSET
- BATT3_VOLT_MULT
- BATT3_VOLT_PIN
- BATT3_WATT_MAX
- BATT4_AMP_OFFSET
- BATT4_AMP_PERVLT
- BATT4_ARM_MAH
- BATT4_ARM_VOLT
- BATT4_CAPACITY
- BATT4_CHANNEL
- BATT4_CRT_MAH
- BATT4_CRT_VOLT
- BATT4_CURR_MULT
- BATT4_CURR_PIN
- BATT4_ESC_INDEX
- BATT4_ESC_MASK
- BATT4_FL_FF
- BATT4_FL_FLTR
- BATT4_FL_FS
- BATT4_FL_FT
- BATT4_FL_OFF
- BATT4_FL_PIN
- BATT4_FL_VLT_MIN
- BATT4_FL_V_MULT
- BATT4_FS_CRT_ACT
- BATT4_FS_LOW_ACT
- BATT4_FS_VOLTSRC
- BATT4_I2C_ADDR
- BATT4_I2C_BUS
- BATT4_LOW_MAH
- BATT4_LOW_TIMER
- BATT4_LOW_VOLT
- BATT4_MAX_AMPS
- BATT4_MAX_VOLT
- BATT4_MONITOR
- BATT4_OPTIONS
- BATT4_SERIAL_NUM
- BATT4_SHUNT
- BATT4_SUM_MASK
- BATT4_VLT_OFFSET
- BATT4_VOLT_MULT
- BATT4_VOLT_PIN
- BATT4_WATT_MAX
- BATT5_AMP_OFFSET
- BATT5_AMP_PERVLT
- BATT5_ARM_MAH
- BATT5_ARM_VOLT
- BATT5_CAPACITY
- BATT5_CHANNEL
- BATT5_CRT_MAH
- BATT5_CRT_VOLT
- BATT5_CURR_MULT
- BATT5_CURR_PIN
- BATT5_ESC_INDEX
- BATT5_ESC_MASK
- BATT5_FL_FF
- BATT5_FL_FLTR
- BATT5_FL_FS
- BATT5_FL_FT
- BATT5_FL_OFF
- BATT5_FL_PIN
- BATT5_FL_VLT_MIN
- BATT5_FL_V_MULT
- BATT5_FS_CRT_ACT
- BATT5_FS_LOW_ACT
- BATT5_FS_VOLTSRC
- BATT5_I2C_ADDR
- BATT5_I2C_BUS
- BATT5_LOW_MAH
- BATT5_LOW_TIMER
- BATT5_LOW_VOLT
- BATT5_MAX_AMPS
- BATT5_MAX_VOLT
- BATT5_MONITOR
- BATT5_OPTIONS
- BATT5_SERIAL_NUM
- BATT5_SHUNT
- BATT5_SUM_MASK
- BATT5_VLT_OFFSET
- BATT5_VOLT_MULT
- BATT5_VOLT_PIN
- BATT5_WATT_MAX
- BATT6_AMP_OFFSET
- BATT6_AMP_PERVLT
- BATT6_ARM_MAH
- BATT6_ARM_VOLT
- BATT6_CAPACITY
- BATT6_CHANNEL
- BATT6_CRT_MAH
- BATT6_CRT_VOLT
- BATT6_CURR_MULT
- BATT6_CURR_PIN
- BATT6_ESC_INDEX
- BATT6_ESC_MASK
- BATT6_FL_FF
- BATT6_FL_FLTR
- BATT6_FL_FS
- BATT6_FL_FT
- BATT6_FL_OFF
- BATT6_FL_PIN
- BATT6_FL_VLT_MIN
- BATT6_FL_V_MULT
- BATT6_FS_CRT_ACT
- BATT6_FS_LOW_ACT
- BATT6_FS_VOLTSRC
- BATT6_I2C_ADDR
- BATT6_I2C_BUS
- BATT6_LOW_MAH
- BATT6_LOW_TIMER
- BATT6_LOW_VOLT
- BATT6_MAX_AMPS
- BATT6_MAX_VOLT
- BATT6_MONITOR
- BATT6_OPTIONS
- BATT6_SERIAL_NUM
- BATT6_SHUNT
- BATT6_SUM_MASK
- BATT6_VLT_OFFSET
- BATT6_VOLT_MULT
- BATT6_VOLT_PIN
- BATT6_WATT_MAX
- BATT7_AMP_OFFSET
- BATT7_AMP_PERVLT
- BATT7_ARM_MAH
- BATT7_ARM_VOLT
- BATT7_CAPACITY
- BATT7_CHANNEL
- BATT7_CRT_MAH
- BATT7_CRT_VOLT
- BATT7_CURR_MULT
- BATT7_CURR_PIN
- BATT7_ESC_INDEX
- BATT7_ESC_MASK
- BATT7_FL_FF
- BATT7_FL_FLTR
- BATT7_FL_FS
- BATT7_FL_FT
- BATT7_FL_OFF
- BATT7_FL_PIN
- BATT7_FL_VLT_MIN
- BATT7_FL_V_MULT
- BATT7_FS_CRT_ACT
- BATT7_FS_LOW_ACT
- BATT7_FS_VOLTSRC
- BATT7_I2C_ADDR
- BATT7_I2C_BUS
- BATT7_LOW_MAH
- BATT7_LOW_TIMER
- BATT7_LOW_VOLT
- BATT7_MAX_AMPS
- BATT7_MAX_VOLT
- BATT7_MONITOR
- BATT7_OPTIONS
- BATT7_SERIAL_NUM
- BATT7_SHUNT
- BATT7_SUM_MASK
- BATT7_VLT_OFFSET
- BATT7_VOLT_MULT
- BATT7_VOLT_PIN
- BATT7_WATT_MAX
- BATT8_AMP_OFFSET
- BATT8_AMP_PERVLT
- BATT8_ARM_MAH
- BATT8_ARM_VOLT
- BATT8_CAPACITY
- BATT8_CHANNEL
- BATT8_CRT_MAH
- BATT8_CRT_VOLT
- BATT8_CURR_MULT
- BATT8_CURR_PIN
- BATT8_ESC_INDEX
- BATT8_ESC_MASK
- BATT8_FL_FF
- BATT8_FL_FLTR
- BATT8_FL_FS
- BATT8_FL_FT
- BATT8_FL_OFF
- BATT8_FL_PIN
- BATT8_FL_VLT_MIN
- BATT8_FL_V_MULT
- BATT8_FS_CRT_ACT
- BATT8_FS_LOW_ACT
- BATT8_FS_VOLTSRC
- BATT8_I2C_ADDR
- BATT8_I2C_BUS
- BATT8_LOW_MAH
- BATT8_LOW_TIMER
- BATT8_LOW_VOLT
- BATT8_MAX_AMPS
- BATT8_MAX_VOLT
- BATT8_MONITOR
- BATT8_OPTIONS
- BATT8_SERIAL_NUM
- BATT8_SHUNT
- BATT8_SUM_MASK
- BATT8_VLT_OFFSET
- BATT8_VOLT_MULT
- BATT8_VOLT_PIN
- BATT8_WATT_MAX
- BATT9_AMP_OFFSET
- BATT9_AMP_PERVLT
- BATT9_ARM_MAH
- BATT9_ARM_VOLT
- BATT9_CAPACITY
- BATT9_CHANNEL
- BATT9_CRT_MAH
- BATT9_CRT_VOLT
- BATT9_CURR_MULT
- BATT9_CURR_PIN
- BATT9_ESC_INDEX
- BATT9_ESC_MASK
- BATT9_FL_FF
- BATT9_FL_FLTR
- BATT9_FL_FS
- BATT9_FL_FT
- BATT9_FL_OFF
- BATT9_FL_PIN
- BATT9_FL_VLT_MIN
- BATT9_FL_V_MULT
- BATT9_FS_CRT_ACT
- BATT9_FS_LOW_ACT
- BATT9_FS_VOLTSRC
- BATT9_I2C_ADDR
- BATT9_I2C_BUS
- BATT9_LOW_MAH
- BATT9_LOW_TIMER
- BATT9_LOW_VOLT
- BATT9_MAX_AMPS
- BATT9_MAX_VOLT
- BATT9_MONITOR
- BATT9_OPTIONS
- BATT9_SERIAL_NUM
- BATT9_SHUNT
- BATT9_SUM_MASK
- BATT9_VLT_OFFSET
- BATT9_VOLT_MULT
- BATT9_VOLT_PIN
- BATT9_WATT_MAX
- BATTA_AMP_OFFSET
- BATTA_AMP_PERVLT
- BATTA_ARM_MAH
- BATTA_ARM_VOLT
- BATTA_CAPACITY
- BATTA_CHANNEL
- BATTA_CRT_MAH
- BATTA_CRT_VOLT
- BATTA_CURR_MULT
- BATTA_CURR_PIN
- BATTA_ESC_INDEX
- BATTA_ESC_MASK
- BATTA_FL_FF
- BATTA_FL_FLTR
- BATTA_FL_FS
- BATTA_FL_FT
- BATTA_FL_OFF
- BATTA_FL_PIN
- BATTA_FL_VLT_MIN
- BATTA_FL_V_MULT
- BATTA_FS_CRT_ACT
- BATTA_FS_LOW_ACT
- BATTA_FS_VOLTSRC
- BATTA_I2C_ADDR
- BATTA_I2C_BUS
- BATTA_LOW_MAH
- BATTA_LOW_TIMER
- BATTA_LOW_VOLT
- BATTA_MAX_AMPS
- BATTA_MAX_VOLT
- BATTA_MONITOR
- BATTA_OPTIONS
- BATTA_SERIAL_NUM
- BATTA_SHUNT
- BATTA_SUM_MASK
- BATTA_VLT_OFFSET
- BATTA_VOLT_MULT
- BATTA_VOLT_PIN
- BATTA_WATT_MAX
- BATTB_AMP_OFFSET
- BATTB_AMP_PERVLT
- BATTB_ARM_MAH
- BATTB_ARM_VOLT
- BATTB_CAPACITY
- BATTB_CHANNEL
- BATTB_CRT_MAH
- BATTB_CRT_VOLT
- BATTB_CURR_MULT
- BATTB_CURR_PIN
- BATTB_ESC_INDEX
- BATTB_ESC_MASK
- BATTB_FL_FF
- BATTB_FL_FLTR
- BATTB_FL_FS
- BATTB_FL_FT
- BATTB_FL_OFF
- BATTB_FL_PIN
- BATTB_FL_VLT_MIN
- BATTB_FL_V_MULT
- BATTB_FS_CRT_ACT
- BATTB_FS_LOW_ACT
- BATTB_FS_VOLTSRC
- BATTB_I2C_ADDR
- BATTB_I2C_BUS
- BATTB_LOW_MAH
- BATTB_LOW_TIMER
- BATTB_LOW_VOLT
- BATTB_MAX_AMPS
- BATTB_MAX_VOLT
- BATTB_MONITOR
- BATTB_OPTIONS
- BATTB_SERIAL_NUM
- BATTB_SHUNT
- BATTB_SUM_MASK
- BATTB_VLT_OFFSET
- BATTB_VOLT_MULT
- BATTB_VOLT_PIN
- BATTB_WATT_MAX
- BATTC_AMP_OFFSET
- BATTC_AMP_PERVLT
- BATTC_ARM_MAH
- BATTC_ARM_VOLT
- BATTC_CAPACITY
- BATTC_CHANNEL
- BATTC_CRT_MAH
- BATTC_CRT_VOLT
- BATTC_CURR_MULT
- BATTC_CURR_PIN
- BATTC_ESC_INDEX
- BATTC_ESC_MASK
- BATTC_FL_FF
- BATTC_FL_FLTR
- BATTC_FL_FS
- BATTC_FL_FT
- BATTC_FL_OFF
- BATTC_FL_PIN
- BATTC_FL_VLT_MIN
- BATTC_FL_V_MULT
- BATTC_FS_CRT_ACT
- BATTC_FS_LOW_ACT
- BATTC_FS_VOLTSRC
- BATTC_I2C_ADDR
- BATTC_I2C_BUS
- BATTC_LOW_MAH
- BATTC_LOW_TIMER
- BATTC_LOW_VOLT
- BATTC_MAX_AMPS
- BATTC_MAX_VOLT
- BATTC_MONITOR
- BATTC_OPTIONS
- BATTC_SERIAL_NUM
- BATTC_SHUNT
- BATTC_SUM_MASK
- BATTC_VLT_OFFSET
- BATTC_VOLT_MULT
- BATTC_VOLT_PIN
- BATTC_WATT_MAX
- BATTD_AMP_OFFSET
- BATTD_AMP_PERVLT
- BATTD_ARM_MAH
- BATTD_ARM_VOLT
- BATTD_CAPACITY
- BATTD_CHANNEL
- BATTD_CRT_MAH
- BATTD_CRT_VOLT
- BATTD_CURR_MULT
- BATTD_CURR_PIN
- BATTD_ESC_INDEX
- BATTD_ESC_MASK
- BATTD_FL_FF
- BATTD_FL_FLTR
- BATTD_FL_FS
- BATTD_FL_FT
- BATTD_FL_OFF
- BATTD_FL_PIN
- BATTD_FL_VLT_MIN
- BATTD_FL_V_MULT
- BATTD_FS_CRT_ACT
- BATTD_FS_LOW_ACT
- BATTD_FS_VOLTSRC
- BATTD_I2C_ADDR
- BATTD_I2C_BUS
- BATTD_LOW_MAH
- BATTD_LOW_TIMER
- BATTD_LOW_VOLT
- BATTD_MAX_AMPS
- BATTD_MAX_VOLT
- BATTD_MONITOR
- BATTD_OPTIONS
- BATTD_SERIAL_NUM
- BATTD_SHUNT
- BATTD_SUM_MASK
- BATTD_VLT_OFFSET
- BATTD_VOLT_MULT
- BATTD_VOLT_PIN
- BATTD_WATT_MAX
- BATTE_AMP_OFFSET
- BATTE_AMP_PERVLT
- BATTE_ARM_MAH
- BATTE_ARM_VOLT
- BATTE_CAPACITY
- BATTE_CHANNEL
- BATTE_CRT_MAH
- BATTE_CRT_VOLT
- BATTE_CURR_MULT
- BATTE_CURR_PIN
- BATTE_ESC_INDEX
- BATTE_ESC_MASK
- BATTE_FL_FF
- BATTE_FL_FLTR
- BATTE_FL_FS
- BATTE_FL_FT
- BATTE_FL_OFF
- BATTE_FL_PIN
- BATTE_FL_VLT_MIN
- BATTE_FL_V_MULT
- BATTE_FS_CRT_ACT
- BATTE_FS_LOW_ACT
- BATTE_FS_VOLTSRC
- BATTE_I2C_ADDR
- BATTE_I2C_BUS
- BATTE_LOW_MAH
- BATTE_LOW_TIMER
- BATTE_LOW_VOLT
- BATTE_MAX_AMPS
- BATTE_MAX_VOLT
- BATTE_MONITOR
- BATTE_OPTIONS
- BATTE_SERIAL_NUM
- BATTE_SHUNT
- BATTE_SUM_MASK
- BATTE_VLT_OFFSET
- BATTE_VOLT_MULT
- BATTE_VOLT_PIN
- BATTE_WATT_MAX
- BATTF_AMP_OFFSET
- BATTF_AMP_PERVLT
- BATTF_ARM_MAH
- BATTF_ARM_VOLT
- BATTF_CAPACITY
- BATTF_CHANNEL
- BATTF_CRT_MAH
- BATTF_CRT_VOLT
- BATTF_CURR_MULT
- BATTF_CURR_PIN
- BATTF_ESC_INDEX
- BATTF_ESC_MASK
- BATTF_FL_FF
- BATTF_FL_FLTR
- BATTF_FL_FS
- BATTF_FL_FT
- BATTF_FL_OFF
- BATTF_FL_PIN
- BATTF_FL_VLT_MIN
- BATTF_FL_V_MULT
- BATTF_FS_CRT_ACT
- BATTF_FS_LOW_ACT
- BATTF_FS_VOLTSRC
- BATTF_I2C_ADDR
- BATTF_I2C_BUS
- BATTF_LOW_MAH
- BATTF_LOW_TIMER
- BATTF_LOW_VOLT
- BATTF_MAX_AMPS
- BATTF_MAX_VOLT
- BATTF_MONITOR
- BATTF_OPTIONS
- BATTF_SERIAL_NUM
- BATTF_SHUNT
- BATTF_SUM_MASK
- BATTF_VLT_OFFSET
- BATTF_VOLT_MULT
- BATTF_VOLT_PIN
- BATTF_WATT_MAX
- BATTG_AMP_OFFSET
- BATTG_AMP_PERVLT
- BATTG_ARM_MAH
- BATTG_ARM_VOLT
- BATTG_CAPACITY
- BATTG_CHANNEL
- BATTG_CRT_MAH
- BATTG_CRT_VOLT
- BATTG_CURR_MULT
- BATTG_CURR_PIN
- BATTG_ESC_INDEX
- BATTG_ESC_MASK
- BATTG_FL_FF
- BATTG_FL_FLTR
- BATTG_FL_FS
- BATTG_FL_FT
- BATTG_FL_OFF
- BATTG_FL_PIN
- BATTG_FL_VLT_MIN
- BATTG_FL_V_MULT
- BATTG_FS_CRT_ACT
- BATTG_FS_LOW_ACT
- BATTG_FS_VOLTSRC
- BATTG_I2C_ADDR
- BATTG_I2C_BUS
- BATTG_LOW_MAH
- BATTG_LOW_TIMER
- BATTG_LOW_VOLT
- BATTG_MAX_AMPS
- BATTG_MAX_VOLT
- BATTG_MONITOR
- BATTG_OPTIONS
- BATTG_SERIAL_NUM
- BATTG_SHUNT
- BATTG_SUM_MASK
- BATTG_VLT_OFFSET
- BATTG_VOLT_MULT
- BATTG_VOLT_PIN
- BATTG_WATT_MAX
- BATT_AMP_OFFSET
- BATT_AMP_PERVLT
- BATT_ARM_MAH
- BATT_ARM_VOLT
- BATT_CAPACITY
- BATT_CHANNEL
- BATT_CRT_MAH
- BATT_CRT_VOLT
- BATT_CURR_MULT
- BATT_CURR_PIN
- BATT_ESC_INDEX
- BATT_ESC_MASK
- BATT_FL_FF
- BATT_FL_FLTR
- BATT_FL_FS
- BATT_FL_FT
- BATT_FL_OFF
- BATT_FL_PIN
- BATT_FL_VLT_MIN
- BATT_FL_V_MULT
- BATT_FS_CRT_ACT
- BATT_FS_LOW_ACT
- BATT_FS_VOLTSRC
- BATT_I2C_ADDR
- BATT_I2C_BUS
- BATT_LOW_MAH
- BATT_LOW_TIMER
- BATT_LOW_VOLT
- BATT_MAX_AMPS
- BATT_MAX_VOLT
- BATT_MONITOR
- BATT_OPTIONS
- BATT_SERIAL_NUM
- BATT_SHUNT
- BATT_SUM_MASK
- BATT_VLT_OFFSET
- BATT_VOLT_MULT
- BATT_VOLT_PIN
- BATT_WATT_MAX
