name: engine
description: ArduPilot engine parameters
version: schema
schema_params:
- EFI_COEF1
- EFI_COEF2
- EFI_FUEL_DENS
- EFI_THRLIN_COEF1
- EFI_THRLIN_COEF2
- EFI_THRLIN_COEF3
- EFI_THRLIN_EN
- EFI_THRLIN_OFS
- EFI_TYPE
- ESC_TLM_MAV_OFS
- GEN_L_IDLE_TEMP
- GEN_L_IDLE_TH
- GEN_L_IDLE_TH_H
- GEN_L_MNT_TIME
- GEN_L_OVER_TEMP
- GEN_L_RUNTIME
- GEN_L_RUN_TEMP
- GEN_OPTIONS
- GEN_TYPE
- ICE_ENABLE
- ICE_IDLE_DB
- ICE_IDLE_PCT
- ICE_IDLE_RPM
- ICE_IDLE_SLEW
- ICE_OPTIONS
- ICE_PWM_IGN_OFF
- ICE_PWM_IGN_ON
- ICE_PWM_STRT_OFF
- ICE_PWM_STRT_ON
- ICE_REDLINE_RPM
- ICE_RPM_CHAN
- ICE_RPM_THRESH
- ICE_STARTCHN_MIN
- ICE_STARTER_TIME
- ICE_START_CHAN
- ICE_START_DELAY
- ICE_START_PCT
- ICE_STRT_MX_RTRY
