name: rc
description: ArduPilot rc parameters
version: schema
schema_params:
- RC10_DZ
- RC10_MAX
- RC10_MIN
- RC10_OPTION
- RC10_REVERSED
- RC10_TRIM
- RC11_DZ
- RC11_MAX
- RC11_MIN
- RC11_OPTION
- RC11_REVERSED
- RC11_TRIM
- RC12_DZ
- RC12_MAX
- RC12_MIN
- RC12_OPTION
- RC12_REVERSED
- RC12_TRIM
- RC13_DZ
- RC13_MAX
- RC13_MIN
- RC13_OPTION
- RC13_REVERSED
- RC13_TRIM
- RC14_DZ
- RC14_MAX
- RC14_MIN
- RC14_OPTION
- RC14_REVERSED
- RC14_TRIM
- RC15_DZ
- RC15_MAX
- RC15_MIN
- RC15_OPTION
- RC15_REVERSED
- RC15_TRIM
- RC16_DZ
- RC16_MAX
- RC16_MIN
- RC16_OPTION
- RC16_REVERSED
- RC16_TRIM
- RC1_DZ
- RC1_MAX
- RC1_MIN
- RC1_OPTION
- RC1_REVERSED
- RC1_TRIM
- RC2_DZ
- RC2_MAX
- RC2_MIN
- RC2_OPTION
- RC2_REVERSED
- RC2_TRIM
- RC3_DZ
- RC3_MAX
- RC3_MIN
- RC3_OPTION
- RC3_REVERSED
- RC3_TRIM
- RC4_DZ
- RC4_MAX
- RC4_MIN
- RC4_OPTION
- RC4_REVERSED
- RC4_TRIM
- RC5_DZ
- RC5_MAX
- RC5_MIN
- RC5_OPTION
- RC5_REVERSED
- RC5_TRIM
- RC6_DZ
- RC6_MAX
- RC6_MIN
- RC6_OPTION
- RC6_REVERSED
- RC6_TRIM
- RC7_DZ
- RC7_MAX
- RC7_MIN
- RC7_OPTION
- RC7_REVERSED
- RC7_TRIM
- RC8_DZ
- RC8_MAX
- RC8_MIN
- RC8_OPTION
- RC8_REVERSED
- RC8_TRIM
- RC9_DZ
- RC9_MAX
- RC9_MIN
- RC9_OPTION
- RC9_REVERSED
- RC9_TRIM
- RCMAP_PITCH
- RCMAP_ROLL
- RCMAP_THROTTLE
- RCMAP_YAW
- RC_FS_TIMEOUT
- RC_OPTIONS
- RC_OVERRIDE_TIME
- RC_PROTOCOLS
