name: rangefinder
description: ArduPilot rangefinder parameters
version: schema
schema_params:
- PLND_ACC_P_NSE
- PLND_ALT_MAX
- PLND_ALT_MIN
- PLND_BUS
- PLND_CAM_POS_X
- PLND_CAM_POS_Y
- PLND_CAM_POS_Z
- PLND_ENABLED
- PLND_EST_TYPE
- PLND_LAG
- PLND_LAND_OFS_X
- PLND_LAND_OFS_Y
- PLND_OPTIONS
- PLND_RET_BEHAVE
- PLND_RET_MAX
- PLND_STRICT
- PLND_TIMEOUT
- PLND_TYPE
- PLND_XY_DIST_MAX
- PLND_YAW_ALIGN
- RNGFND1_ADDR
- RNGFND1_FUNCTION
- RNGFND1_GNDCLR
- RNGFND1_GRF_RATE
- RNGFND1_GRF_RET
- RNGFND1_GRF_ST
- RNGFND1_MAX
- RNGFND1_MIN
- RNGFND1_OFFSET
- RNGFND1_ORIENT
- RNGFND1_PIN
- RNGFND1_POS_X
- RNGFND1_POS_Y
- RNGFND1_POS_Z
- RNGFND1_PWRRNG
- RNGFND1_RECV_ID
- RNGFND1_RMETRIC
- RNGFND1_SCALING
- RNGFND1_SNR_MIN
- RNGFND1_STOP_PIN
- RNGFND1_TYPE
- RNGFND1_WSP_AVG
- RNGFND1_WSP_BAUD
- RNGFND1_WSP_FRQ
- RNGFND1_WSP_MAVG
- RNGFND1_WSP_MEDF
- RNGFND1_WSP_THR
- RNGFND2_ADDR
- RNGFND2_FUNCTION
- RNGFND2_GNDCLR
- RNGFND2_GRF_RATE
- RNGFND2_GRF_RET
- RNGFND2_GRF_ST
- RNGFND2_MAX
- RNGFND2_MIN
- RNGFND2_OFFSET
- RNGFND2_ORIENT
- RNGFND2_PIN
- RNGFND2_POS_X
- RNGFND2_POS_Y
- RNGFND2_POS_Z
- RNGFND2_PWRRNG
- RNGFND2_RECV_ID
- RNGFND2_RMETRIC
- RNGFND2_SCALING
- RNGFND2_SNR_MIN
- RNGFND2_STOP_PIN
- RNGFND2_TYPE
- RNGFND2_WSP_AVG
- RNGFND2_WSP_BAUD
- RNGFND2_WSP_FRQ
- RNGFND2_WSP_MAVG
- RNGFND2_WSP_MEDF
- RNGFND2_WSP_THR
- RNGFND3_ADDR
- RNGFND3_FUNCTION
- RNGFND3_GNDCLR
- RNGFND3_GRF_RATE
- RNGFND3_GRF_RET
- RNGFND3_GRF_ST
- RNGFND3_MAX
- RNGFND3_MIN
- RNGFND3_OFFSET
- RNGFND3_ORIENT
- RNGFND3_PIN
- RNGFND3_POS_X
- RNGFND3_POS_Y
- RNGFND3_POS_Z
- RNGFND3_PWRRNG
- RNGFND3_RECV_ID
- RNGFND3_RMETRIC
- RNGFND3_SCALING
- RNGFND3_SNR_MIN
- RNGFND3_STOP_PIN
- RNGFND3_TYPE
- RNGFND3_WSP_AVG
- RNGFND3_WSP_BAUD
- RNGFND3_WSP_FRQ
- RNGFND3_WSP_MAVG
- RNGFND3_WSP_MEDF
- RNGFND3_WSP_THR
- RNGFND4_ADDR
- RNGFND4_FUNCTION
- RNGFND4_GNDCLR
- RNGFND4_GRF_RATE
- RNGFND4_GRF_RET
- RNGFND4_GRF_ST
- RNGFND4_MAX
- RNGFND4_MIN
- RNGFND4_OFFSET
- RNGFND4_ORIENT
- RNGFND4_PIN
- RNGFND4_POS_X
- RNGFND4_POS_Y
- RNGFND4_POS_Z
- RNGFND4_PWRRNG
- RNGFND4_RECV_ID
- RNGFND4_RMETRIC
- RNGFND4_SCALING
- RNGFND4_SNR_MIN
- RNGFND4_STOP_PIN
- RNGFND4_TYPE
- RNGFND4_WSP_AVG
- RNGFND4_WSP_BAUD
- RNGFND4_WSP_FRQ
- RNGFND4_WSP_MAVG
- RNGFND4_WSP_MEDF
- RNGFND4_WSP_THR
- RNGFND5_ADDR
- RNGFND5_FUNCTION
- RNGFND5_GNDCLR
- RNGFND5_GRF_RATE
- RNGFND5_GRF_RET
- RNGFND5_GRF_ST
- RNGFND5_MAX
- RNGFND5_MIN
- RNGFND5_OFFSET
- RNGFND5_ORIENT
- RNGFND5_PIN
- RNGFND5_POS_X
- RNGFND5_POS_Y
- RNGFND5_POS_Z
- RNGFND5_PWRRNG
- RNGFND5_RECV_ID
- RNGFND5_RMETRIC
- RNGFND5_SCALING
- RNGFND5_SNR_MIN
- RNGFND5_STOP_PIN
- RNGFND5_TYPE
- RNGFND5_WSP_AVG
- RNGFND5_WSP_BAUD
- RNGFND5_WSP_FRQ
- RNGFND5_WSP_MAVG
- RNGFND5_WSP_MEDF
- RNGFND5_WSP_THR
- RNGFND6_ADDR
- RNGFND6_FUNCTION
- RNGFND6_GNDCLR
- RNGFND6_GRF_RATE
- RNGFND6_GRF_RET
- RNGFND6_GRF_ST
- RNGFND6_MAX
- RNGFND6_MIN
- RNGFND6_OFFSET
- RNGFND6_ORIENT
- RNGFND6_PIN
- RNGFND6_POS_X
- RNGFND6_POS_Y
- RNGFND6_POS_Z
- RNGFND6_PWRRNG
- RNGFND6_RECV_ID
- RNGFND6_RMETRIC
- RNGFND6_SCALING
- RNGFND6_SNR_MIN
- RNGFND6_STOP_PIN
- RNGFND6_TYPE
- RNGFND6_WSP_AVG
- RNGFND6_WSP_BAUD
- RNGFND6_WSP_FRQ
- RNGFND6_WSP_MAVG
- RNGFND6_WSP_MEDF
- RNGFND6_WSP_THR
- RNGFND7_ADDR
- RNGFND7_FUNCTION
- RNGFND7_GNDCLR
- RNGFND7_GRF_RATE
- RNGFND7_GRF_RET
- RNGFND7_GRF_ST
- RNGFND7_MAX
- RNGFND7_MIN
- RNGFND7_OFFSET
- RNGFND7_ORIENT
- RNGFND7_PIN
- RNGFND7_POS_X
- RNGFND7_POS_Y
- RNGFND7_POS_Z
- RNGFND7_PWRRNG
- RNGFND7_RECV_ID
- RNGFND7_RMETRIC
- RNGFND7_SCALING
- RNGFND7_SNR_MIN
- RNGFND7_STOP_PIN
- RNGFND7_TYPE
- RNGFND7_WSP_AVG
- RNGFND7_WSP_BAUD
- RNGFND7_WSP_FRQ
- RNGFND7_WSP_MAVG
- RNGFND7_WSP_MEDF
- RNGFND7_WSP_THR
- RNGFND8_ADDR
- RNGFND8_FUNCTION
- RNGFND8_GNDCLR
- RNGFND8_GRF_RATE
- RNGFND8_GRF_RET
- RNGFND8_GRF_ST
- RNGFND8_MAX
- RNGFND8_MIN
- RNGFND8_OFFSET
- RNGFND8_ORIENT
- RNGFND8_PIN
- RNGFND8_POS_X
- RNGFND8_POS_Y
- RNGFND8_POS_Z
- RNGFND8_PWRRNG
- RNGFND8_RECV_ID
- RNGFND8_RMETRIC
- RNGFND8_SCALING
- RNGFND8_SNR_MIN
- RNGFND8_STOP_PIN
- RNGFND8_TYPE
- RNGFND8_WSP_AVG
- RNGFND8_WSP_BAUD
- RNGFND8_WSP_FRQ
- RNGFND8_WSP_MAVG
- RNGFND8_WSP_MEDF
- RNGFND8_WSP_THR
- RNGFND9_ADDR
- RNGFND9_FUNCTION
- RNGFND9_GNDCLR
- RNGFND9_GRF_RATE
- RNGFND9_GRF_RET
- RNGFND9_GRF_ST
- RNGFND9_MAX
- RNGFND9_MIN
- RNGFND9_OFFSET
- RNGFND9_ORIENT
- RNGFND9_PIN
- RNGFND9_POS_X
- RNGFND9_POS_Y
- RNGFND9_POS_Z
- RNGFND9_PWRRNG
- RNGFND9_RECV_ID
- RNGFND9_RMETRIC
- RNGFND9_SCALING
- RNGFND9_SNR_MIN
- RNGFND9_STOP_PIN
- RNGFND9_TYPE
- RNGFND9_WSP_AVG
- RNGFND9_WSP_BAUD
- RNGFND9_WSP_FRQ
- RNGFND9_WSP_MAVG
- RNGFND9_WSP_MEDF
- RNGFND9_WSP_THR
- RNGFNDA_ADDR
- RNGFNDA_FUNCTION
- RNGFNDA_GNDCLR
- RNGFNDA_GRF_RATE
- RNGFNDA_GRF_RET
- RNGFNDA_GRF_ST
- RNGFNDA_MAX
- RNGFNDA_MIN
- RNGFNDA_OFFSET
- RNGFNDA_ORIENT
- RNGFNDA_PIN
- RNGFNDA_POS_X
- RNGFNDA_POS_Y
- RNGFNDA_POS_Z
- RNGFNDA_PWRRNG
- RNGFNDA_RECV_ID
- RNGFNDA_RMETRIC
- RNGFNDA_SCALING
- RNGFNDA_SNR_MIN
- RNGFNDA_STOP_PIN
- RNGFNDA_TYPE
- RNGFNDA_WSP_AVG
- RNGFNDA_WSP_BAUD
- RNGFNDA_WSP_FRQ
- RNGFNDA_WSP_MAVG
- RNGFNDA_WSP_MEDF
- RNGFNDA_WSP_THR
