name: notifications
description: ArduPilot notifications parameters
version: schema
schema_params:
- BTN_ENABLE
- BTN_FUNC1
- BTN_FUNC2
- BTN_FUNC3
- BTN_FUNC4
- BTN_OPTIONS1
- BTN_OPTIONS2
- BTN_OPTIONS3
- BTN_OPTIONS4
- BTN_PIN1
- BTN_PIN2
- BTN_PIN3
- BTN_PIN4
- BTN_REPORT_SEND
- FRSKY_DNLINK1_ID
- FRSKY_DNLINK2_ID
- FRSKY_DNLINK_ID
- FRSKY_OPTIONS
- FRSKY_UPLINK_ID
- NTF_BUZZ_ON_LVL
- NTF_BUZZ_PIN
- NTF_BUZZ_TYPES
- NTF_BUZZ_VOLUME
- NTF_DISPLAY_TYPE
- NTF_LED_BRIGHT
- NTF_LED_LEN
- NTF_LED_OVERRIDE
- NTF_LED_TYPES
- NTF_OREO_THEME
