name: landing
description: ArduPilot landing parameters
version: schema
schema_params:
- AUTOLAND_CLIMB
- AUTOLAND_DIR_OFF
- AUTOLAND_OPTIONS
- AUTOLAND_WP_ALT
- AUTOLAND_WP_DIST
- LAND_ABORT_DEG
- LAND_ABORT_THR
- LAND_DISARMDELAY
- LAND_DS_ABORTALT
- LAND_DS_AIL_SCL
- LAND_DS_APP_EXT
- LAND_DS_ARSP_MAX
- LAND_DS_ARSP_MIN
- LAND_DS_D
- LAND_DS_ELEV_PWM
- LAND_DS_I
- LAND_DS_IMAX
- LAND_DS_L1
- LAND_DS_L1_I
- LAND_DS_L1_TCON
- LAND_DS_P
- LAND_DS_SLEW_SPD
- LAND_DS_SLOPE_A
- LAND_DS_SLOPE_B
- LAND_DS_V_DWN
- LAND_DS_V_FWD
- LAND_DS_YAW_LIM
- LAND_FLAP_PERCNT
- LAND_FLARE_AIM
- LAND_FLARE_ALT
- LAND_FLARE_SEC
- LAND_OPTIONS
- LAND_PF_ALT
- LAND_PF_ARSPD
- LAND_PF_SEC
- LAND_PITCH_DEG
- LAND_SLOPE_RCALC
- LAND_THEN_NEUTRL
- LAND_THR_SLEW
- LAND_TYPE
- LAND_WIND_COMP
- TKOFF_ALT
- TKOFF_DIST
- TKOFF_GND_PITCH
- TKOFF_LVL_ALT
- TKOFF_LVL_PITCH
