params:
  OSD1_ACRVOLT_EN: 0
  OSD1_ACRVOLT_X: 24
  OSD1_ACRVOLT_Y: 4
  OSD1_ALTITUDE_EN: 1
  OSD1_ALTITUDE_X: 24
  OSD1_ALTITUDE_Y: 5
  OSD1_ARMING_EN: 0
  OSD1_ARMING_X: 12
  OSD1_ARMING_Y: 3
  OSD1_ASPD1_EN: 0
  OSD1_ASPD1_X: 8
  OSD1_ASPD1_Y: 3
  OSD1_ASPD2_EN: 0
  OSD1_ASPD2_X: 3
  OSD1_ASPD2_Y: 4
  OSD1_ASPEED_EN: 1
  OSD1_ASPEED_X: 24
  OSD1_ASPEED_Y: 9
  OSD1_ATEMP_EN: 0
  OSD1_ATEMP_X: 14
  OSD1_ATEMP_Y: 5
  OSD1_AVGCELLV_EN: 1
  OSD1_AVGCELLV_X: 2
  OSD1_AVGCELLV_Y: 13
  OSD1_BAT2USED_EN: 0
  OSD1_BAT2USED_X: 0
  OSD1_BAT2USED_Y: 0
  OSD1_BAT2_VLT_EN: 0
  OSD1_BAT2_VLT_X: 0
  OSD1_BAT2_VLT_Y: 0
  OSD1_BATTBAR_EN: 0
  OSD1_BATTBAR_X: 14
  OSD1_BATTBAR_Y: 6
  OSD1_BATUSED_EN: 0
  OSD1_BATUSED_X: 24
  OSD1_BATUSED_Y: 13
  OSD1_BAT_VOLT_EN: 0
  OSD1_BAT_VOLT_X: 2
  OSD1_BAT_VOLT_Y: 14
  OSD1_BTEMP_EN: 0
  OSD1_BTEMP_X: 0
  OSD1_BTEMP_Y: 0
  OSD1_CALLSIGN_EN: 1
  OSD1_CALLSIGN_X: 12
  OSD1_CALLSIGN_Y: 14
  OSD1_CELLVOLT_EN: 0
  OSD1_CELLVOLT_X: 3
  OSD1_CELLVOLT_Y: 14
  OSD1_CHAN_MAX: 0
  OSD1_CHAN_MIN: 0
  OSD1_CLIMBEFF_EN: 0
  OSD1_CLIMBEFF_X: 0
  OSD1_CLIMBEFF_Y: 0
  OSD1_CLK_EN: 0
  OSD1_CLK_X: 14
  OSD1_CLK_Y: 8
  OSD1_COMPASS_EN: 0
  OSD1_COMPASS_X: 14
  OSD1_COMPASS_Y: 2
  OSD1_CRSSHAIR_EN: 0
  OSD1_CRSSHAIR_X: 0
  OSD1_CRSSHAIR_Y: 0
  OSD1_CURRENT2_EN: 0
  OSD1_CURRENT2_X: 0
  OSD1_CURRENT2_Y: 0
  OSD1_CURRENT_EN: 1
  OSD1_CURRENT_X: 2
  OSD1_CURRENT_Y: 9
  OSD1_DIST_EN: 1
  OSD1_DIST_X: 13
  OSD1_DIST_Y: 12
  OSD1_EFF_EN: 1
  OSD1_EFF_X: 2
  OSD1_EFF_Y: 11
  OSD1_ENABLE: 1
  OSD1_ESCAMPS_EN: 1
  OSD1_ESCAMPS_X: 3
  OSD1_ESCAMPS_Y: 8
  OSD1_ESCRPM_EN: 0
  OSD1_ESCRPM_X: 24
  OSD1_ESCRPM_Y: 4
  OSD1_ESCTEMP_EN: 1
  OSD1_ESCTEMP_X: 25
  OSD1_ESCTEMP_Y: 8
  OSD1_ESC_IDX: 0
  OSD1_FENCE_EN: 0
  OSD1_FENCE_X: 14
  OSD1_FENCE_Y: 9
  OSD1_FLTIME_EN: 1
  OSD1_FLTIME_X: 22
  OSD1_FLTIME_Y: 14
  OSD1_FLTMODE_EN: 1
  OSD1_FLTMODE_X: 13
  OSD1_FLTMODE_Y: 1
  OSD1_FONT: 0
  OSD1_GPSLAT_EN: 1
  OSD1_GPSLAT_X: 17
  OSD1_GPSLAT_Y: 15
  OSD1_GPSLONG_EN: 1
  OSD1_GPSLONG_X: 0
  OSD1_GPSLONG_Y: 15
  OSD1_GSPEED_EN: 0
  OSD1_GSPEED_X: 22
  OSD1_GSPEED_Y: 10
  OSD1_HDOP_EN: 1
  OSD1_HDOP_X: 1
  OSD1_HDOP_Y: 4
  OSD1_HEADING_EN: 0
  OSD1_HEADING_X: 12
  OSD1_HEADING_Y: 1
  OSD1_HOMEDIR_EN: 1
  OSD1_HOMEDIR_X: 12
  OSD1_HOMEDIR_Y: 12
  OSD1_HOMEDIST_EN: 0
  OSD1_HOMEDIST_X: 2
  OSD1_HOMEDIST_Y: 16
  OSD1_HOME_EN: 0
  OSD1_HOME_X: 12
  OSD1_HOME_Y: 13
  OSD1_HORIZON_EN: 1
  OSD1_HORIZON_X: 15
  OSD1_HORIZON_Y: 7
  OSD1_LINK_Q_EN: 1
  OSD1_LINK_Q_X: 3
  OSD1_LINK_Q_Y: 1
  OSD1_MESSAGE_EN: 1
  OSD1_MESSAGE_X: 1
  OSD1_MESSAGE_Y: 10
  OSD1_PITCH_EN: 1
  OSD1_PITCH_X: 13
  OSD1_PITCH_Y: 6
  OSD1_PLUSCODE_EN: 0
  OSD1_PLUSCODE_X: 0
  OSD1_PLUSCODE_Y: 0
  OSD1_POWER_EN: 0
  OSD1_POWER_X: 14
  OSD1_POWER_Y: 5
  OSD1_RESTVOLT_EN: 0
  OSD1_RESTVOLT_X: 15
  OSD1_RESTVOLT_Y: 12
  OSD1_RNGF_EN: 0
  OSD1_RNGF_X: 12
  OSD1_RNGF_Y: 7
  OSD1_ROLL_EN: 1
  OSD1_ROLL_X: 13
  OSD1_ROLL_Y: 8
  OSD1_RPM_EN: 0
  OSD1_RPM_X: 25
  OSD1_RPM_Y: 8
  OSD1_RSSI_EN: 1
  OSD1_RSSI_X: 3
  OSD1_RSSI_Y: 2
  OSD1_SATS_EN: 1
  OSD1_SATS_X: 1
  OSD1_SATS_Y: 3
  OSD1_SIDEBARS_EN: 0
  OSD1_SIDEBARS_X: 0
  OSD1_SIDEBARS_Y: 0
  OSD1_STATS_EN: 0
  OSD1_STATS_X: 13
  OSD1_STATS_Y: 4
  OSD1_TEMP_EN: 0
  OSD1_TEMP_X: 13
  OSD1_TEMP_Y: 3
  OSD1_TER_HGT_EN: 0
  OSD1_TER_HGT_X: 23
  OSD1_TER_HGT_Y: 7
  OSD1_THROTTLE_EN: 1
  OSD1_THROTTLE_X: 0
  OSD1_THROTTLE_Y: 8
  OSD1_TXT_RES: 0
  OSD1_VSPEED_EN: 1
  OSD1_VSPEED_X: 25
  OSD1_VSPEED_Y: 6
  OSD1_VTX_PWR_EN: 1
  OSD1_VTX_PWR_X: 25
  OSD1_VTX_PWR_Y: 1
  OSD1_WAYPOINT_EN: 0
  OSD1_WAYPOINT_X: 0
  OSD1_WAYPOINT_Y: 0
  OSD1_WIND_EN: 0
  OSD1_WIND_X: 2
  OSD1_WIND_Y: 12
  OSD1_XTRACK_EN: 0
  OSD1_XTRACK_X: 0
  OSD1_XTRACK_Y: 0
  OSD2_ACRVOLT_EN: 0
  OSD2_ACRVOLT_X: 24
  OSD2_ACRVOLT_Y: 4
  OSD2_ALTITUDE_EN: 0
  OSD2_ALTITUDE_X: 23
  OSD2_ALTITUDE_Y: 8
  OSD2_ARMING_EN: 0
  OSD2_ARMING_X: 1
  OSD2_ARMING_Y: 1
  OSD2_ASPD1_EN: 0
  OSD2_ASPD1_X: 0
  OSD2_ASPD1_Y: 0
  OSD2_ASPD2_EN: 0
  OSD2_ASPD2_X: 0
  OSD2_ASPD2_Y: 0
  OSD2_ASPEED_EN: 0
  OSD2_ASPEED_X: 2
  OSD2_ASPEED_Y: 13
  OSD2_ATEMP_EN: 0
  OSD2_ATEMP_X: 0
  OSD2_ATEMP_Y: 0
  OSD2_AVGCELLV_EN: 0
  OSD2_AVGCELLV_X: 24
  OSD2_AVGCELLV_Y: 3
  OSD2_BAT2USED_EN: 0
  OSD2_BAT2USED_X: 0
  OSD2_BAT2USED_Y: 0
  OSD2_BAT2_VLT_EN: 0
  OSD2_BAT2_VLT_X: 0
  OSD2_BAT2_VLT_Y: 0
  OSD2_BATTBAR_EN: 0
  OSD2_BATTBAR_X: 1
  OSD2_BATTBAR_Y: 1
  OSD2_BATUSED_EN: 0
  OSD2_BATUSED_X: 23
  OSD2_BATUSED_Y: 3
  OSD2_BAT_VOLT_EN: 0
  OSD2_BAT_VOLT_X: 24
  OSD2_BAT_VOLT_Y: 1
  OSD2_BTEMP_EN: 0
  OSD2_BTEMP_X: 0
  OSD2_BTEMP_Y: 0
  OSD2_CALLSIGN_EN: 0
  OSD2_CALLSIGN_X: 0
  OSD2_CALLSIGN_Y: 0
  OSD2_CELLVOLT_EN: 0
  OSD2_CELLVOLT_X: 5
  OSD2_CELLVOLT_Y: 0
  OSD2_CHAN_MAX: 2100
  OSD2_CHAN_MIN: 900
  OSD2_CLIMBEFF_EN: 0
  OSD2_CLIMBEFF_X: 0
  OSD2_CLIMBEFF_Y: 0
  OSD2_CLK_EN: 0
  OSD2_CLK_X: 0
  OSD2_CLK_Y: 0
  OSD2_COMPASS_EN: 0
  OSD2_COMPASS_X: 15
  OSD2_COMPASS_Y: 3
  OSD2_CRSSHAIR_EN: 0
  OSD2_CRSSHAIR_X: 0
  OSD2_CRSSHAIR_Y: 0
  OSD2_CURRENT2_EN: 0
  OSD2_CURRENT2_X: 0
  OSD2_CURRENT2_Y: 0
  OSD2_CURRENT_EN: 0
  OSD2_CURRENT_X: 25
  OSD2_CURRENT_Y: 2
  OSD2_DIST_EN: 0
  OSD2_DIST_X: 22
  OSD2_DIST_Y: 11
  OSD2_EFF_EN: 0
  OSD2_EFF_X: 22
  OSD2_EFF_Y: 10
  OSD2_ENABLE: 1
  OSD2_ESCAMPS_EN: 0
  OSD2_ESCAMPS_X: 24
  OSD2_ESCAMPS_Y: 14
  OSD2_ESCRPM_EN: 0
  OSD2_ESCRPM_X: 22
  OSD2_ESCRPM_Y: 12
  OSD2_ESCTEMP_EN: 0
  OSD2_ESCTEMP_X: 24
  OSD2_ESCTEMP_Y: 13
  OSD2_ESC_IDX: 0
  OSD2_FENCE_EN: 0
  OSD2_FENCE_X: 14
  OSD2_FENCE_Y: 9
  OSD2_FLTIME_EN: 0
  OSD2_FLTIME_X: 23
  OSD2_FLTIME_Y: 10
  OSD2_FLTMODE_EN: 0
  OSD2_FLTMODE_X: 2
  OSD2_FLTMODE_Y: 8
  OSD2_FONT: 0
  OSD2_GPSLAT_EN: 1
  OSD2_GPSLAT_X: 9
  OSD2_GPSLAT_Y: 13
  OSD2_GPSLONG_EN: 1
  OSD2_GPSLONG_X: 9
  OSD2_GPSLONG_Y: 14
  OSD2_GSPEED_EN: 0
  OSD2_GSPEED_X: 2
  OSD2_GSPEED_Y: 14
  OSD2_HDOP_EN: 0
  OSD2_HDOP_X: 0
  OSD2_HDOP_Y: 0
  OSD2_HEADING_EN: 0
  OSD2_HEADING_X: 13
  OSD2_HEADING_Y: 2
  OSD2_HOMEDIR_EN: 1
  OSD2_HOMEDIR_X: 12
  OSD2_HOMEDIR_Y: 11
  OSD2_HOMEDIST_EN: 1
  OSD2_HOMEDIST_X: 11
  OSD2_HOMEDIST_Y: 10
  OSD2_HOME_EN: 0
  OSD2_HOME_X: 14
  OSD2_HOME_Y: 1
  OSD2_HORIZON_EN: 0
  OSD2_HORIZON_X: 14
  OSD2_HORIZON_Y: 8
  OSD2_LINK_Q_EN: 1
  OSD2_LINK_Q_X: 25
  OSD2_LINK_Q_Y: 7
  OSD2_MESSAGE_EN: 0
  OSD2_MESSAGE_X: 2
  OSD2_MESSAGE_Y: 6
  OSD2_PITCH_EN: 0
  OSD2_PITCH_X: 0
  OSD2_PITCH_Y: 0
  OSD2_PLUSCODE_EN: 0
  OSD2_PLUSCODE_X: 0
  OSD2_PLUSCODE_Y: 0
  OSD2_POWER_EN: 0
  OSD2_POWER_X: 7
  OSD2_POWER_Y: 1
  OSD2_RESTVOLT_EN: 0
  OSD2_RESTVOLT_X: 24
  OSD2_RESTVOLT_Y: 2
  OSD2_RNGF_EN: 0
  OSD2_RNGF_X: 0
  OSD2_RNGF_Y: 0
  OSD2_ROLL_EN: 0
  OSD2_ROLL_X: 0
  OSD2_ROLL_Y: 0
  OSD2_RPM_EN: 0
  OSD2_RPM_X: 2
  OSD2_RPM_Y: 2
  OSD2_RSSI_EN: 0
  OSD2_RSSI_X: 14
  OSD2_RSSI_Y: 10
  OSD2_SATS_EN: 0
  OSD2_SATS_X: 1
  OSD2_SATS_Y: 3
  OSD2_SIDEBARS_EN: 0
  OSD2_SIDEBARS_X: 4
  OSD2_SIDEBARS_Y: 5
  OSD2_STATS_EN: 0
  OSD2_STATS_X: 0
  OSD2_STATS_Y: 0
  OSD2_TEMP_EN: 0
  OSD2_TEMP_X: 0
  OSD2_TEMP_Y: 0
  OSD2_TER_HGT_EN: 0
  OSD2_TER_HGT_X: 23
  OSD2_TER_HGT_Y: 7
  OSD2_THROTTLE_EN: 0
  OSD2_THROTTLE_X: 24
  OSD2_THROTTLE_Y: 11
  OSD2_TXT_RES: 0
  OSD2_VSPEED_EN: 0
  OSD2_VSPEED_X: 24
  OSD2_VSPEED_Y: 9
  OSD2_VTX_PWR_EN: 0
  OSD2_VTX_PWR_X: 0
  OSD2_VTX_PWR_Y: 0
  OSD2_WAYPOINT_EN: 0
  OSD2_WAYPOINT_X: 0
  OSD2_WAYPOINT_Y: 0
  OSD2_WIND_EN: 0
  OSD2_WIND_X: 2
  OSD2_WIND_Y: 12
  OSD2_XTRACK_EN: 0
  OSD2_XTRACK_X: 0
  OSD2_XTRACK_Y: 0
  OSD3_ENABLE: 0
  OSD3_ESC_IDX: 0
  OSD3_FONT: 0
  OSD3_LINK_Q_EN: 0
  OSD3_LINK_Q_X: 1
  OSD3_LINK_Q_Y: 1
  OSD3_TXT_RES: 0
  OSD4_ENABLE: 0
  OSD4_ESC_IDX: 0
  OSD4_FONT: 0
  OSD4_LINK_Q_EN: 0
  OSD4_LINK_Q_X: 1
  OSD4_LINK_Q_Y: 1
  OSD4_TXT_RES: 0
  OSD5_ENABLE: 0
  OSD6_ENABLE: 0
  OSD_ARM_SCR: 0
  OSD_BTN_DELAY: 300
  OSD_CELL_COUNT: 6
  OSD_CHAN: 7
  OSD_DSARM_SCR: 0
  OSD_FONT: 0
  OSD_FS_SCR: 0
  OSD_H_OFFSET: 17
  OSD_MSG_TIME: 10
  OSD_OPTIONS: 1
  OSD_SB_H_OFS: 6
  OSD_SB_V_EXT: 0
  OSD_SW_METHOD: 0
  OSD_TYPE: 1
  OSD_TYPE2: 0
  OSD_UNITS: 0
  OSD_V_OFFSET: 15
  OSD_W_ACRVOLT: 3.200000047683716
  OSD_W_AVGCELLV: 3.200000047683716
  OSD_W_BATVOLT: 12.800000190734863
  OSD_W_NSAT: 5
  OSD_W_RESTVOLT: 10
  OSD_W_RSSI: 30
  OSD_W_TERR: -1
