name: camera
description: ArduPilot camera parameters
version: schema
schema_params:
- CAM1_DURATION
- CAM1_FEEDBAK_PIN
- CAM1_FEEDBAK_POL
- CAM1_HFOV
- CAM1_INTRVAL_MIN
- CAM1_MNT_INST
- CAM1_OPTIONS
- CAM1_RC_BTN_DELAY
- CAM1_RC_BT_DELAY
- CAM1_RC_CONTROL
- CAM1_RC_FEATURES
- CAM1_RC_MDE_DELAY
- CAM1_RC_TYPE
- CAM1_RELAY_ON
- CAM1_SERVO_OFF
- CAM1_SERVO_ON
- CAM1_TRIGG_DIST
- CAM1_TYPE
- CAM1_VFOV
- CAM2_DURATION
- CAM2_FEEDBAK_PIN
- CAM2_FEEDBAK_POL
- CAM2_HFOV
- CAM2_INTRVAL_MIN
- CAM2_MNT_INST
- CAM2_OPTIONS
- CAM2_RC_BTN_DELAY
- CAM2_RC_BT_DELAY
- CAM2_RC_CONTROL
- CAM2_RC_FEATURES
- CAM2_RC_MDE_DELAY
- CAM2_RC_TYPE
- CAM2_RELAY_ON
- CAM2_SERVO_OFF
- CAM2_SERVO_ON
- CAM2_TRIGG_DIST
- CAM2_TYPE
- CAM2_VFOV
- CAM_AUTO_ONLY
- CAM_MAX_ROLL
