name: rpm
description: ArduPilot rpm parameters
version: schema
schema_params:
- RPM1_DC_ID
- RPM1_ESC_INDEX
- RPM1_ESC_MASK
- RPM1_MAX
- RPM1_MIN
- RPM1_MIN_QUAL
- RPM1_PIN
- RPM1_SCALING
- RPM1_TYPE
- RPM2_DC_ID
- RPM2_ESC_INDEX
- RPM2_ESC_MASK
- RPM2_MAX
- RPM2_MIN
- RPM2_MIN_QUAL
- RPM2_PIN
- RPM2_SCALING
- RPM2_TYPE
- RPM3_DC_ID
- RPM3_ESC_INDEX
- RPM3_ESC_MASK
- RPM3_MAX
- RPM3_MIN
- RPM3_MIN_QUAL
- RPM3_PIN
- RPM3_SCALING
- RPM3_TYPE
- RPM4_DC_ID
- RPM4_ESC_INDEX
- RPM4_ESC_MASK
- RPM4_MAX
- RPM4_MIN
- RPM4_MIN_QUAL
- RPM4_PIN
- RPM4_SCALING
- RPM4_TYPE
